<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE IntfImg:Images
[
    <!ELEMENT IntfImg:Image  EMPTY>
    <!ATTLIST IntfImg:Image  IntfImg:Name CDATA #REQUIRED
                             IntfImg:Trans (Yes | No) "No"
                             IntfImg:TransAt CDATA "0,0">
    <!ELEMENT IntfImg:Scope  (IntfImg:Scope | IntfImg:Image)*>
    <!ATTLIST IntfImg:Scope  IntfImg:Name CDATA #REQUIRED>
    <!ELEMENT IntfImg:Images (IntfImg:Scope+)>
]>

<IntfImg:Images>

    <IntfImg:Scope IntfImg:Name="System">
        <IntfImg:Scope IntfImg:Name="ImgPacks">
            <IntfImg:Scope IntfImg:Name="Ripper">
                <IntfImg:Scope IntfImg:Name="ExpressVu">
                    <IntfImg:Image IntfImg:Name="abc-hdtv.png"/>
                    <IntfImg:Image IntfImg:Name="aboriginal_peoples_tvnet.png"/>
                    <IntfImg:Image IntfImg:Name="adrenaline_drive.png"/>
                    <IntfImg:Image IntfImg:Name="ang_dating_daan.png"/>
                    <IntfImg:Image IntfImg:Name="artv_quebec.png"/>
                    <IntfImg:Image IntfImg:Name="art_global_us.png"/>
                    <IntfImg:Image IntfImg:Name="art_movies_us.png"/>
                    <IntfImg:Image IntfImg:Name="asn_halifax.png"/>
                    <IntfImg:Image IntfImg:Name="assemblee_national_quebec.png"/>
                    <IntfImg:Image IntfImg:Name="atv_halifax.png"/>
                    <IntfImg:Image IntfImg:Name="atv_moncton.png"/>
                    <IntfImg:Image IntfImg:Name="atv_saint_john_nb.png"/>
                    <IntfImg:Image IntfImg:Name="atv_sydney_ca.png"/>
                    <IntfImg:Image IntfImg:Name="baby_channel.png"/>
                    <IntfImg:Image IntfImg:Name="bbc_canada.png"/>
                    <IntfImg:Image IntfImg:Name="bbc_kids_ca.png"/>
                    <IntfImg:Image IntfImg:Name="bc_legislature.png"/>
                    <IntfImg:Image IntfImg:Name="biography.png"/>
                    <IntfImg:Image IntfImg:Name="blue_hustler.png"/>
                    <IntfImg:Image IntfImg:Name="bluvu_fra.png"/>
                    <IntfImg:Image IntfImg:Name="booktv_ca.png"/>
                    <IntfImg:Image IntfImg:Name="bpm_tv.png"/>
                    <IntfImg:Image IntfImg:Name="bravo_ca.png"/>
                    <IntfImg:Image IntfImg:Name="broadcast_news.png"/>
                    <IntfImg:Image IntfImg:Name="cablepulse24.png"/>
                    <IntfImg:Image IntfImg:Name="canald.png"/>
                    <IntfImg:Image IntfImg:Name="canalvie.png"/>
                    <IntfImg:Image IntfImg:Name="canal_indigo.png"/>
                    <IntfImg:Image IntfImg:Name="canal_vox_ca_qc.png"/>
                    <IntfImg:Image IntfImg:Name="casino_gaming_tv.png"/>
                    <IntfImg:Image IntfImg:Name="cbc_alberta.png"/>
                    <IntfImg:Image IntfImg:Name="cbc_edmonton.png"/>
                    <IntfImg:Image IntfImg:Name="cbc_hd.png"/>
                    <IntfImg:Image IntfImg:Name="cbc_manitoba.png"/>
                    <IntfImg:Image IntfImg:Name="cbc_montreal.png"/>
                    <IntfImg:Image IntfImg:Name="cbc_newsworld.png"/>
                    <IntfImg:Image IntfImg:Name="cbc_north.png"/>
                    <IntfImg:Image IntfImg:Name="cbc_src.png"/>
                    <IntfImg:Image IntfImg:Name="cbc_tv.png"/>
                    <IntfImg:Image IntfImg:Name="cblt_toronto.png"/>
                    <IntfImg:Image IntfImg:Name="cbs-hd.png"/>
                    <IntfImg:Image IntfImg:Name="cfap_tqs_quebec.png"/>
                    <IntfImg:Image IntfImg:Name="cfcf_montreal.png"/>
                    <IntfImg:Image IntfImg:Name="cfcm_tele4_quebec.png"/>
                    <IntfImg:Image IntfImg:Name="cfcn_calgary.png"/>
                    <IntfImg:Image IntfImg:Name="cfem_rouyn.png"/>
                    <IntfImg:Image IntfImg:Name="cfer_quebec.png"/>
                    <IntfImg:Image IntfImg:Name="cfjc_tv7_kamloops.png"/>
                    <IntfImg:Image IntfImg:Name="cfjp_montreal.png"/>
                    <IntfImg:Image IntfImg:Name="cfmt_omni1_toronto.png"/>
                    <IntfImg:Image IntfImg:Name="cfnx_canada.png"/>
                    <IntfImg:Image IntfImg:Name="cfn_canadian_forces_net.png"/>
                    <IntfImg:Image IntfImg:Name="cfpl_a_channel_london.png"/>
                    <IntfImg:Image IntfImg:Name="cfqc_tv_saskatoon.png"/>
                    <IntfImg:Image IntfImg:Name="cfre_global_regina.png"/>
                    <IntfImg:Image IntfImg:Name="cfrn_edmonton.png"/>
                    <IntfImg:Image IntfImg:Name="cfrt_tv.png"/>
                    <IntfImg:Image IntfImg:Name="cfrt_tv_fr.png"/>
                    <IntfImg:Image IntfImg:Name="cfsk_global_saskatoon.png"/>
                    <IntfImg:Image IntfImg:Name="cftk_terrace.png"/>
                    <IntfImg:Image IntfImg:Name="cftm_montreal.png"/>
                    <IntfImg:Image IntfImg:Name="cfto_toronto.png"/>
                    <IntfImg:Image IntfImg:Name="cftu_canal_savoir.png"/>
                    <IntfImg:Image IntfImg:Name="channel_m.png"/>
                    <IntfImg:Image IntfImg:Name="chan_global_vancouver.png"/>
                    <IntfImg:Image IntfImg:Name="chau_tva_carleton.png"/>
                    <IntfImg:Image IntfImg:Name="chbc_kelowa.png"/>
                    <IntfImg:Image IntfImg:Name="chch_hamilton.png"/>
                    <IntfImg:Image IntfImg:Name="chek_victoria.png"/>
                    <IntfImg:Image IntfImg:Name="chem_trois_rivieres.png"/>
                    <IntfImg:Image IntfImg:Name="chex_durham_can.png"/>
                    <IntfImg:Image IntfImg:Name="chex_peterborough_can.png"/>
                    <IntfImg:Image IntfImg:Name="chfd_thunder_bay.png"/>
                    <IntfImg:Image IntfImg:Name="chlt_sherbrooke.png"/>
                    <IntfImg:Image IntfImg:Name="chmi_city_tv_winnipeg.png"/>
                    <IntfImg:Image IntfImg:Name="chot_tva_hull.png"/>
                    <IntfImg:Image IntfImg:Name="chro_a_channel_ottawa.png"/>
                    <IntfImg:Image IntfImg:Name="chwi_a_channel_wingham.png"/>
                    <IntfImg:Image IntfImg:Name="cian_access13_calgary.png"/>
                    <IntfImg:Image IntfImg:Name="cicc_yorkton.png"/>
                    <IntfImg:Image IntfImg:Name="cict_global_calgary.png"/>
                    <IntfImg:Image IntfImg:Name="cihf_global_halifax.png"/>
                    <IntfImg:Image IntfImg:Name="ciii_global_toronto.png"/>
                    <IntfImg:Image IntfImg:Name="cimt_tva_riviere_du_loup.png"/>
                    <IntfImg:Image IntfImg:Name="cine_pop.png"/>
                    <IntfImg:Image IntfImg:Name="cipa_prince_albert.png"/>
                    <IntfImg:Image IntfImg:Name="cisa_global_lethbridge.png"/>
                    <IntfImg:Image IntfImg:Name="citl_lloydminster.png"/>
                    <IntfImg:Image IntfImg:Name="cits_crossroads36_burlingto.png"/>
                    <IntfImg:Image IntfImg:Name="citv_global_edmonton.png"/>
                    <IntfImg:Image IntfImg:Name="city_city_tv_toronto.png"/>
                    <IntfImg:Image IntfImg:Name="city_tv_hd.png"/>
                    <IntfImg:Image IntfImg:Name="civi_a_channel_victoria.png"/>
                    <IntfImg:Image IntfImg:Name="civt_vancouver.png"/>
                    <IntfImg:Image IntfImg:Name="cjal_access9_edmonton.png"/>
                    <IntfImg:Image IntfImg:Name="cjbn_kenora.png"/>
                    <IntfImg:Image IntfImg:Name="cjdc_dawson_creek.png"/>
                    <IntfImg:Image IntfImg:Name="cjil_miraclechannel_lethbri.png"/>
                    <IntfImg:Image IntfImg:Name="cjmt_omni2_toronto.png"/>
                    <IntfImg:Image IntfImg:Name="cjnt_montreal.png"/>
                    <IntfImg:Image IntfImg:Name="cjoh_ottawa.png"/>
                    <IntfImg:Image IntfImg:Name="cjon_ntv_st_john_nf.png"/>
                    <IntfImg:Image IntfImg:Name="cjpm_saguenay.png"/>
                    <IntfImg:Image IntfImg:Name="cjtv_kenora.png"/>
                    <IntfImg:Image IntfImg:Name="ckal_city_tv_calgary.png"/>
                    <IntfImg:Image IntfImg:Name="ckck_regina_ctv.png"/>
                    <IntfImg:Image IntfImg:Name="ckco_kitchener.png"/>
                    <IntfImg:Image IntfImg:Name="ckem_city_tv_edmonton.png"/>
                    <IntfImg:Image IntfImg:Name="ckmi_global_montreal.png"/>
                    <IntfImg:Image IntfImg:Name="cknd_global_winnipeg.png"/>
                    <IntfImg:Image IntfImg:Name="ckno_knowledge_5_vancouver.png"/>
                    <IntfImg:Image IntfImg:Name="ckpg_tv2_prince_george.png"/>
                    <IntfImg:Image IntfImg:Name="ckpr_thunder_bay.png"/>
                    <IntfImg:Image IntfImg:Name="ckrd_globaltv_red_deer.png"/>
                    <IntfImg:Image IntfImg:Name="cksa_lloydminster.png"/>
                    <IntfImg:Image IntfImg:Name="ckvr_a_channel_barrie_toron.png"/>
                    <IntfImg:Image IntfImg:Name="ckvu_city_tv_vancouver.png"/>
                    <IntfImg:Image IntfImg:Name="ckws_kingston.png"/>
                    <IntfImg:Image IntfImg:Name="ckxt_sun_tv_toronto.png"/>
                    <IntfImg:Image IntfImg:Name="cky_tv_winnipeg.png"/>
                    <IntfImg:Image IntfImg:Name="clt.png"/>
                    <IntfImg:Image IntfImg:Name="cmt_ca.png"/>
                    <IntfImg:Image IntfImg:Name="comedynetwork.png"/>
                    <IntfImg:Image IntfImg:Name="comic_strip.png"/>
                    <IntfImg:Image IntfImg:Name="cool_tv_winnipeg.png"/>
                    <IntfImg:Image IntfImg:Name="country.png"/>
                    <IntfImg:Image IntfImg:Name="courttv_ca.png"/>
                    <IntfImg:Image IntfImg:Name="cpac.png"/>
                    <IntfImg:Image IntfImg:Name="ctbc.png"/>
                    <IntfImg:Image IntfImg:Name="ctv_hd.png"/>
                    <IntfImg:Image IntfImg:Name="ctv_newsnet.png"/>
                    <IntfImg:Image IntfImg:Name="deja_view.png"/>
                    <IntfImg:Image IntfImg:Name="discovery-hd.png"/>
                    <IntfImg:Image IntfImg:Name="discovery_times.png"/>
                    <IntfImg:Image IntfImg:Name="documentary_channel_ca.png"/>
                    <IntfImg:Image IntfImg:Name="drive_in_classics.png"/>
                    <IntfImg:Image IntfImg:Name="edge_tv.png"/>
                    <IntfImg:Image IntfImg:Name="edmonton_oilers_ppv.png"/>
                    <IntfImg:Image IntfImg:Name="encore_avenue.png"/>
                    <IntfImg:Image IntfImg:Name="espnclassic_ca.png"/>
                    <IntfImg:Image IntfImg:Name="evasion.png"/>
                    <IntfImg:Image IntfImg:Name="evision.png"/>
                    <IntfImg:Image IntfImg:Name="fairchildtv.png"/>
                    <IntfImg:Image IntfImg:Name="family.png"/>
                    <IntfImg:Image IntfImg:Name="familynet.png"/>
                    <IntfImg:Image IntfImg:Name="fashiontv_ca.png"/>
                    <IntfImg:Image IntfImg:Name="flames_tv_calgary.png"/>
                    <IntfImg:Image IntfImg:Name="foodnetwork_ca.png"/>
                    <IntfImg:Image IntfImg:Name="fox-hd.png"/>
                    <IntfImg:Image IntfImg:Name="foxsportsworld_ca.png"/>
                    <IntfImg:Image IntfImg:Name="g4_tech_tv.png"/>
                    <IntfImg:Image IntfImg:Name="global_hd.png"/>
                    <IntfImg:Image IntfImg:Name="green_channel.png"/>
                    <IntfImg:Image IntfImg:Name="heartland_road.png"/>
                    <IntfImg:Image IntfImg:Name="hgtvcanada.png"/>
                    <IntfImg:Image IntfImg:Name="historia.png"/>
                    <IntfImg:Image IntfImg:Name="historytv.png"/>
                    <IntfImg:Image IntfImg:Name="hustler_tv.png"/>
                    <IntfImg:Image IntfImg:Name="ifc_ca.png"/>
                    <IntfImg:Image IntfImg:Name="itbc.png"/>
                    <IntfImg:Image IntfImg:Name="i_channel.png"/>
                    <IntfImg:Image IntfImg:Name="knowledgenetwork.png"/>
                    <IntfImg:Image IntfImg:Name="knowledgetv.png"/>
                    <IntfImg:Image IntfImg:Name="know_tv.png"/>
                    <IntfImg:Image IntfImg:Name="lcn_ca.png"/>
                    <IntfImg:Image IntfImg:Name="leafs_tv.png"/>
                    <IntfImg:Image IntfImg:Name="life_create.png"/>
                    <IntfImg:Image IntfImg:Name="life_network.png"/>
                    <IntfImg:Image IntfImg:Name="lightforallnations.png"/>
                    <IntfImg:Image IntfImg:Name="lonestar.png"/>
                    <IntfImg:Image IntfImg:Name="mctv_north_bay.png"/>
                    <IntfImg:Image IntfImg:Name="mctv_sault_ste_marie.png"/>
                    <IntfImg:Image IntfImg:Name="mctv_sudbury.png"/>
                    <IntfImg:Image IntfImg:Name="mctv_timmins.png"/>
                    <IntfImg:Image IntfImg:Name="men_tv.png"/>
                    <IntfImg:Image IntfImg:Name="meteomedia.png"/>
                    <IntfImg:Image IntfImg:Name="movieola.png"/>
                    <IntfImg:Image IntfImg:Name="movie_central.png"/>
                    <IntfImg:Image IntfImg:Name="movie_central_hd.png"/>
                    <IntfImg:Image IntfImg:Name="mtv_hits.png"/>
                    <IntfImg:Image IntfImg:Name="mtv_jams.png"/>
                    <IntfImg:Image IntfImg:Name="muchmoremusic.png"/>
                    <IntfImg:Image IntfImg:Name="muchmusic.png"/>
                    <IntfImg:Image IntfImg:Name="much_loud.png"/>
                    <IntfImg:Image IntfImg:Name="much_more_retro.png"/>
                    <IntfImg:Image IntfImg:Name="much_vibe.png"/>
                    <IntfImg:Image IntfImg:Name="musimax.png"/>
                    <IntfImg:Image IntfImg:Name="musiqueplus.png"/>
                    <IntfImg:Image IntfImg:Name="mystere_quebec.png"/>
                    <IntfImg:Image IntfImg:Name="mystery.png"/>
                    <IntfImg:Image IntfImg:Name="m_escape.png"/>
                    <IntfImg:Image IntfImg:Name="m_excess.png"/>
                    <IntfImg:Image IntfImg:Name="m_fest.png"/>
                    <IntfImg:Image IntfImg:Name="m_fun.png"/>
                    <IntfImg:Image IntfImg:Name="m_hd.png"/>
                    <IntfImg:Image IntfImg:Name="m_more.png"/>
                    <IntfImg:Image IntfImg:Name="m_pix.png"/>
                    <IntfImg:Image IntfImg:Name="m_pix_too.png"/>
                    <IntfImg:Image IntfImg:Name="nascar_incar.png"/>
                    <IntfImg:Image IntfImg:Name="nbc-hd.png"/>
                    <IntfImg:Image IntfImg:Name="nhl_center_ice.png"/>
                    <IntfImg:Image IntfImg:Name="ntv_ca.png"/>
                    <IntfImg:Image IntfImg:Name="nw_cablenews_can.png"/>
                    <IntfImg:Image IntfImg:Name="oasis_hd.png"/>
                    <IntfImg:Image IntfImg:Name="odyssey_tv_network_ca.png"/>
                    <IntfImg:Image IntfImg:Name="one_ca.png"/>
                    <IntfImg:Image IntfImg:Name="ontario_legislature.png"/>
                    <IntfImg:Image IntfImg:Name="outdoorlife.png"/>
                    <IntfImg:Image IntfImg:Name="out_tv.png"/>
                    <IntfImg:Image IntfImg:Name="pbs-hd.png"/>
                    <IntfImg:Image IntfImg:Name="planete_ca.png"/>
                    <IntfImg:Image IntfImg:Name="play_tv_ca.png"/>
                    <IntfImg:Image IntfImg:Name="pridevision.png"/>
                    <IntfImg:Image IntfImg:Name="prime_tv_can.png"/>
                    <IntfImg:Image IntfImg:Name="punch_much.png"/>
                    <IntfImg:Image IntfImg:Name="raptorstv.png"/>
                    <IntfImg:Image IntfImg:Name="raptors_tv_hd.png"/>
                    <IntfImg:Image IntfImg:Name="razer.png"/>
                    <IntfImg:Image IntfImg:Name="rds.png"/>
                    <IntfImg:Image IntfImg:Name="ris_info_sports.png"/>
                    <IntfImg:Image IntfImg:Name="robtv.png"/>
                    <IntfImg:Image IntfImg:Name="rogers_sportsnet_east.png"/>
                    <IntfImg:Image IntfImg:Name="rogers_sportsnet_hd.png"/>
                    <IntfImg:Image IntfImg:Name="rogers_sportsnet_ontario.png"/>
                    <IntfImg:Image IntfImg:Name="rogers_sportsnet_pacific.png"/>
                    <IntfImg:Image IntfImg:Name="rogers_sportsnet_west.png"/>
                    <IntfImg:Image IntfImg:Name="rogers_tv.png"/>
                    <IntfImg:Image IntfImg:Name="russian_hour.png"/>
                    <IntfImg:Image IntfImg:Name="salt_and_light_tv.png"/>
                    <IntfImg:Image IntfImg:Name="saskatchewan_legislative.png"/>
                    <IntfImg:Image IntfImg:Name="scn.png"/>
                    <IntfImg:Image IntfImg:Name="scream.png"/>
                    <IntfImg:Image IntfImg:Name="series_plus.png"/>
                    <IntfImg:Image IntfImg:Name="sextv.png"/>
                    <IntfImg:Image IntfImg:Name="shadow_lane.png"/>
                    <IntfImg:Image IntfImg:Name="shoppers_drug_mart.png"/>
                    <IntfImg:Image IntfImg:Name="shop_tv_ca.png"/>
                    <IntfImg:Image IntfImg:Name="showcase_action.png"/>
                    <IntfImg:Image IntfImg:Name="showcase_ca.png"/>
                    <IntfImg:Image IntfImg:Name="showcase_diva.png"/>
                    <IntfImg:Image IntfImg:Name="silver_screen_classics.png"/>
                    <IntfImg:Image IntfImg:Name="space.png"/>
                    <IntfImg:Image IntfImg:Name="spike_tv.png"/>
                    <IntfImg:Image IntfImg:Name="starchoice_info.png"/>
                    <IntfImg:Image IntfImg:Name="star_tv_ca.png"/>
                    <IntfImg:Image IntfImg:Name="superchancan.png"/>
                    <IntfImg:Image IntfImg:Name="super_ecran.png"/>
                    <IntfImg:Image IntfImg:Name="super_ecran2.png"/>
                    <IntfImg:Image IntfImg:Name="super_ecran3.png"/>
                    <IntfImg:Image IntfImg:Name="super_ecran4.png"/>
                    <IntfImg:Image IntfImg:Name="super_ecran_demande.png"/>
                    <IntfImg:Image IntfImg:Name="talentvision.png"/>
                    <IntfImg:Image IntfImg:Name="talktv.png"/>
                    <IntfImg:Image IntfImg:Name="tamil_vision_inc.png"/>
                    <IntfImg:Image IntfImg:Name="teleannonces.png"/>
                    <IntfImg:Image IntfImg:Name="telemag_quebec.png"/>
                    <IntfImg:Image IntfImg:Name="telequebec.png"/>
                    <IntfImg:Image IntfImg:Name="teletoon_ca.png"/>
                    <IntfImg:Image IntfImg:Name="tele_latino.png"/>
                    <IntfImg:Image IntfImg:Name="tfo.png"/>
                    <IntfImg:Image IntfImg:Name="the_movie_network.png"/>
                    <IntfImg:Image IntfImg:Name="the_score.png"/>
                    <IntfImg:Image IntfImg:Name="tln_telelatino.png"/>
                    <IntfImg:Image IntfImg:Name="tln_total_living_net.png"/>
                    <IntfImg:Image IntfImg:Name="travel_ctv.png"/>
                    <IntfImg:Image IntfImg:Name="treehouse.png"/>
                    <IntfImg:Image IntfImg:Name="trn_racingnet_ca.png"/>
                    <IntfImg:Image IntfImg:Name="tsc.png"/>
                    <IntfImg:Image IntfImg:Name="tsn.png"/>
                    <IntfImg:Image IntfImg:Name="tsn_hd.png"/>
                    <IntfImg:Image IntfImg:Name="tv5_quebec.png"/>
                    <IntfImg:Image IntfImg:Name="tvland_us.png"/>
                    <IntfImg:Image IntfImg:Name="tvo.png"/>
                    <IntfImg:Image IntfImg:Name="tvplus_media_ca.png"/>
                    <IntfImg:Image IntfImg:Name="vancouver_canucks_ppv.png"/>
                    <IntfImg:Image IntfImg:Name="venus_ca.png"/>
                    <IntfImg:Image IntfImg:Name="viewers_choice.png"/>
                    <IntfImg:Image IntfImg:Name="visiontv.png"/>
                    <IntfImg:Image IntfImg:Name="vrak_tv.png"/>
                    <IntfImg:Image IntfImg:Name="vu_ppv_canada.png"/>
                    <IntfImg:Image IntfImg:Name="weathernetwork_canada.png"/>
                    <IntfImg:Image IntfImg:Name="wetv_thegreenchannel.png"/>
                    <IntfImg:Image IntfImg:Name="wmnb_tv.png"/>
                    <IntfImg:Image IntfImg:Name="wtsn.png"/>
                    <IntfImg:Image IntfImg:Name="w_network.png"/>
                    <IntfImg:Image IntfImg:Name="xtremesports_ca.png"/>
                    <IntfImg:Image IntfImg:Name="youth_tv.png"/>
                    <IntfImg:Image IntfImg:Name="z_tele.png"/>
                </IntfImg:Scope>
            </IntfImg:Scope>
        </IntfImg:Scope>
    </IntfImg:Scope>
</IntfImg:Images>

