<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE IntfImg:Images
[
    <!ELEMENT IntfImg:Image  EMPTY>
    <!ATTLIST IntfImg:Image  IntfImg:Name CDATA #REQUIRED
                             IntfImg:Trans (Yes | No) "No"
                             IntfImg:TransAt CDATA "0,0">
    <!ELEMENT IntfImg:Scope  (IntfImg:Scope | IntfImg:Image)*>
    <!ATTLIST IntfImg:Scope  IntfImg:Name CDATA #REQUIRED>
    <!ELEMENT IntfImg:Images (IntfImg:Scope+)>
]>

<IntfImg:Images>

    <IntfImg:Scope IntfImg:Name="System">
        <IntfImg:Scope IntfImg:Name="ImgPacks">
            <IntfImg:Scope IntfImg:Name="FancyWeather">
                <IntfImg:Scope IntfImg:Name="32x32">
                    <IntfImg:Image IntfImg:Name="0.png"/>
                    <IntfImg:Image IntfImg:Name="1.png"/>
                    <IntfImg:Image IntfImg:Name="2.png"/>
                    <IntfImg:Image IntfImg:Name="3.png"/>
                    <IntfImg:Image IntfImg:Name="4.png"/>
                    <IntfImg:Image IntfImg:Name="5.png"/>
                    <IntfImg:Image IntfImg:Name="6.png"/>
                    <IntfImg:Image IntfImg:Name="7.png"/>
                    <IntfImg:Image IntfImg:Name="8.png"/>
                    <IntfImg:Image IntfImg:Name="9.png"/>
                    <IntfImg:Image IntfImg:Name="10.png"/>
                    <IntfImg:Image IntfImg:Name="11.png"/>
                    <IntfImg:Image IntfImg:Name="12.png"/>
                    <IntfImg:Image IntfImg:Name="13.png"/>
                    <IntfImg:Image IntfImg:Name="14.png"/>
                    <IntfImg:Image IntfImg:Name="15.png"/>
                    <IntfImg:Image IntfImg:Name="16.png"/>
                    <IntfImg:Image IntfImg:Name="17.png"/>
                    <IntfImg:Image IntfImg:Name="18.png"/>
                    <IntfImg:Image IntfImg:Name="19.png"/>
                    <IntfImg:Image IntfImg:Name="20.png"/>
                    <IntfImg:Image IntfImg:Name="21.png"/>
                    <IntfImg:Image IntfImg:Name="22.png"/>
                    <IntfImg:Image IntfImg:Name="23.png"/>
                    <IntfImg:Image IntfImg:Name="24.png"/>
                    <IntfImg:Image IntfImg:Name="25.png"/>
                    <IntfImg:Image IntfImg:Name="26.png"/>
                    <IntfImg:Image IntfImg:Name="27.png"/>
                    <IntfImg:Image IntfImg:Name="28.png"/>
                    <IntfImg:Image IntfImg:Name="29.png"/>
                    <IntfImg:Image IntfImg:Name="30.png"/>
                    <IntfImg:Image IntfImg:Name="31.png"/>
                    <IntfImg:Image IntfImg:Name="32.png"/>
                    <IntfImg:Image IntfImg:Name="33.png"/>
                    <IntfImg:Image IntfImg:Name="34.png"/>
                    <IntfImg:Image IntfImg:Name="35.png"/>
                    <IntfImg:Image IntfImg:Name="36.png"/>
                    <IntfImg:Image IntfImg:Name="37.png"/>
                    <IntfImg:Image IntfImg:Name="38.png"/>
                    <IntfImg:Image IntfImg:Name="39.png"/>
                    <IntfImg:Image IntfImg:Name="40.png"/>
                    <IntfImg:Image IntfImg:Name="41.png"/>
                    <IntfImg:Image IntfImg:Name="42.png"/>
                    <IntfImg:Image IntfImg:Name="43.png"/>
                    <IntfImg:Image IntfImg:Name="44.png"/>
                    <IntfImg:Image IntfImg:Name="45.png"/>
                    <IntfImg:Image IntfImg:Name="46.png"/>
                    <IntfImg:Image IntfImg:Name="47.png"/>
                </IntfImg:Scope>

                <IntfImg:Scope IntfImg:Name="64x64">
                    <IntfImg:Image IntfImg:Name="0.png"/>
                    <IntfImg:Image IntfImg:Name="1.png"/>
                    <IntfImg:Image IntfImg:Name="2.png"/>
                    <IntfImg:Image IntfImg:Name="3.png"/>
                    <IntfImg:Image IntfImg:Name="4.png"/>
                    <IntfImg:Image IntfImg:Name="5.png"/>
                    <IntfImg:Image IntfImg:Name="6.png"/>
                    <IntfImg:Image IntfImg:Name="7.png"/>
                    <IntfImg:Image IntfImg:Name="8.png"/>
                    <IntfImg:Image IntfImg:Name="9.png"/>
                    <IntfImg:Image IntfImg:Name="10.png"/>
                    <IntfImg:Image IntfImg:Name="11.png"/>
                    <IntfImg:Image IntfImg:Name="12.png"/>
                    <IntfImg:Image IntfImg:Name="13.png"/>
                    <IntfImg:Image IntfImg:Name="14.png"/>
                    <IntfImg:Image IntfImg:Name="15.png"/>
                    <IntfImg:Image IntfImg:Name="16.png"/>
                    <IntfImg:Image IntfImg:Name="17.png"/>
                    <IntfImg:Image IntfImg:Name="18.png"/>
                    <IntfImg:Image IntfImg:Name="19.png"/>
                    <IntfImg:Image IntfImg:Name="20.png"/>
                    <IntfImg:Image IntfImg:Name="21.png"/>
                    <IntfImg:Image IntfImg:Name="22.png"/>
                    <IntfImg:Image IntfImg:Name="23.png"/>
                    <IntfImg:Image IntfImg:Name="24.png"/>
                    <IntfImg:Image IntfImg:Name="25.png"/>
                    <IntfImg:Image IntfImg:Name="26.png"/>
                    <IntfImg:Image IntfImg:Name="27.png"/>
                    <IntfImg:Image IntfImg:Name="28.png"/>
                    <IntfImg:Image IntfImg:Name="29.png"/>
                    <IntfImg:Image IntfImg:Name="30.png"/>
                    <IntfImg:Image IntfImg:Name="31.png"/>
                    <IntfImg:Image IntfImg:Name="32.png"/>
                    <IntfImg:Image IntfImg:Name="33.png"/>
                    <IntfImg:Image IntfImg:Name="34.png"/>
                    <IntfImg:Image IntfImg:Name="35.png"/>
                    <IntfImg:Image IntfImg:Name="36.png"/>
                    <IntfImg:Image IntfImg:Name="37.png"/>
                    <IntfImg:Image IntfImg:Name="38.png"/>
                    <IntfImg:Image IntfImg:Name="39.png"/>
                    <IntfImg:Image IntfImg:Name="40.png"/>
                    <IntfImg:Image IntfImg:Name="41.png"/>
                    <IntfImg:Image IntfImg:Name="42.png"/>
                    <IntfImg:Image IntfImg:Name="43.png"/>
                    <IntfImg:Image IntfImg:Name="44.png"/>
                    <IntfImg:Image IntfImg:Name="45.png"/>
                    <IntfImg:Image IntfImg:Name="46.png"/>
                    <IntfImg:Image IntfImg:Name="47.png"/>
                </IntfImg:Scope>

                <IntfImg:Scope IntfImg:Name="128x128">
                    <IntfImg:Image IntfImg:Name="0.png"/>
                    <IntfImg:Image IntfImg:Name="1.png"/>
                    <IntfImg:Image IntfImg:Name="2.png"/>
                    <IntfImg:Image IntfImg:Name="3.png"/>
                    <IntfImg:Image IntfImg:Name="4.png"/>
                    <IntfImg:Image IntfImg:Name="5.png"/>
                    <IntfImg:Image IntfImg:Name="6.png"/>
                    <IntfImg:Image IntfImg:Name="7.png"/>
                    <IntfImg:Image IntfImg:Name="8.png"/>
                    <IntfImg:Image IntfImg:Name="9.png"/>
                    <IntfImg:Image IntfImg:Name="10.png"/>
                    <IntfImg:Image IntfImg:Name="11.png"/>
                    <IntfImg:Image IntfImg:Name="12.png"/>
                    <IntfImg:Image IntfImg:Name="13.png"/>
                    <IntfImg:Image IntfImg:Name="14.png"/>
                    <IntfImg:Image IntfImg:Name="15.png"/>
                    <IntfImg:Image IntfImg:Name="16.png"/>
                    <IntfImg:Image IntfImg:Name="17.png"/>
                    <IntfImg:Image IntfImg:Name="18.png"/>
                    <IntfImg:Image IntfImg:Name="19.png"/>
                    <IntfImg:Image IntfImg:Name="20.png"/>
                    <IntfImg:Image IntfImg:Name="21.png"/>
                    <IntfImg:Image IntfImg:Name="22.png"/>
                    <IntfImg:Image IntfImg:Name="23.png"/>
                    <IntfImg:Image IntfImg:Name="24.png"/>
                    <IntfImg:Image IntfImg:Name="25.png"/>
                    <IntfImg:Image IntfImg:Name="26.png"/>
                    <IntfImg:Image IntfImg:Name="27.png"/>
                    <IntfImg:Image IntfImg:Name="28.png"/>
                    <IntfImg:Image IntfImg:Name="29.png"/>
                    <IntfImg:Image IntfImg:Name="30.png"/>
                    <IntfImg:Image IntfImg:Name="31.png"/>
                    <IntfImg:Image IntfImg:Name="32.png"/>
                    <IntfImg:Image IntfImg:Name="33.png"/>
                    <IntfImg:Image IntfImg:Name="34.png"/>
                    <IntfImg:Image IntfImg:Name="35.png"/>
                    <IntfImg:Image IntfImg:Name="36.png"/>
                    <IntfImg:Image IntfImg:Name="37.png"/>
                    <IntfImg:Image IntfImg:Name="38.png"/>
                    <IntfImg:Image IntfImg:Name="39.png"/>
                    <IntfImg:Image IntfImg:Name="40.png"/>
                    <IntfImg:Image IntfImg:Name="41.png"/>
                    <IntfImg:Image IntfImg:Name="42.png"/>
                    <IntfImg:Image IntfImg:Name="43.png"/>
                    <IntfImg:Image IntfImg:Name="44.png"/>
                    <IntfImg:Image IntfImg:Name="45.png"/>
                    <IntfImg:Image IntfImg:Name="46.png"/>
                    <IntfImg:Image IntfImg:Name="47.png"/>
                </IntfImg:Scope>

                <IntfImg:Scope IntfImg:Name="256x256">
                    <IntfImg:Image IntfImg:Name="0.png"/>
                    <IntfImg:Image IntfImg:Name="1.png"/>
                    <IntfImg:Image IntfImg:Name="2.png"/>
                    <IntfImg:Image IntfImg:Name="3.png"/>
                    <IntfImg:Image IntfImg:Name="4.png"/>
                    <IntfImg:Image IntfImg:Name="5.png"/>
                    <IntfImg:Image IntfImg:Name="6.png"/>
                    <IntfImg:Image IntfImg:Name="7.png"/>
                    <IntfImg:Image IntfImg:Name="8.png"/>
                    <IntfImg:Image IntfImg:Name="9.png"/>
                    <IntfImg:Image IntfImg:Name="10.png"/>
                    <IntfImg:Image IntfImg:Name="11.png"/>
                    <IntfImg:Image IntfImg:Name="12.png"/>
                    <IntfImg:Image IntfImg:Name="13.png"/>
                    <IntfImg:Image IntfImg:Name="14.png"/>
                    <IntfImg:Image IntfImg:Name="15.png"/>
                    <IntfImg:Image IntfImg:Name="16.png"/>
                    <IntfImg:Image IntfImg:Name="17.png"/>
                    <IntfImg:Image IntfImg:Name="18.png"/>
                    <IntfImg:Image IntfImg:Name="19.png"/>
                    <IntfImg:Image IntfImg:Name="20.png"/>
                    <IntfImg:Image IntfImg:Name="21.png"/>
                    <IntfImg:Image IntfImg:Name="22.png"/>
                    <IntfImg:Image IntfImg:Name="23.png"/>
                    <IntfImg:Image IntfImg:Name="24.png"/>
                    <IntfImg:Image IntfImg:Name="25.png"/>
                    <IntfImg:Image IntfImg:Name="26.png"/>
                    <IntfImg:Image IntfImg:Name="27.png"/>
                    <IntfImg:Image IntfImg:Name="28.png"/>
                    <IntfImg:Image IntfImg:Name="29.png"/>
                    <IntfImg:Image IntfImg:Name="30.png"/>
                    <IntfImg:Image IntfImg:Name="31.png"/>
                    <IntfImg:Image IntfImg:Name="32.png"/>
                    <IntfImg:Image IntfImg:Name="33.png"/>
                    <IntfImg:Image IntfImg:Name="34.png"/>
                    <IntfImg:Image IntfImg:Name="35.png"/>
                    <IntfImg:Image IntfImg:Name="36.png"/>
                    <IntfImg:Image IntfImg:Name="37.png"/>
                    <IntfImg:Image IntfImg:Name="38.png"/>
                    <IntfImg:Image IntfImg:Name="39.png"/>
                    <IntfImg:Image IntfImg:Name="40.png"/>
                    <IntfImg:Image IntfImg:Name="41.png"/>
                    <IntfImg:Image IntfImg:Name="42.png"/>
                    <IntfImg:Image IntfImg:Name="43.png"/>
                    <IntfImg:Image IntfImg:Name="44.png"/>
                    <IntfImg:Image IntfImg:Name="45.png"/>
                    <IntfImg:Image IntfImg:Name="46.png"/>
                    <IntfImg:Image IntfImg:Name="47.png"/>
                </IntfImg:Scope>

            </IntfImg:Scope>
        </IntfImg:Scope>
    </IntfImg:Scope>
</IntfImg:Images>

