<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE IntfImg:Images
[
    <!ELEMENT IntfImg:Image  EMPTY>
    <!ATTLIST IntfImg:Image  IntfImg:Name CDATA #REQUIRED
                             IntfImg:Trans (Yes | No) "No"
                             IntfImg:TransAt CDATA "0,0">
    <!ELEMENT IntfImg:Scope  (IntfImg:Scope | IntfImg:Image)*>
    <!ATTLIST IntfImg:Scope  IntfImg:Name CDATA #REQUIRED>
    <!ELEMENT IntfImg:Images (IntfImg:Scope+)>
]>

<!--
  - This pack is for a free set of icons from Glyfx. For each image there
  - is a regular, disabled, and 'hot' version, which we put into separate
  - scopes. We also include a couple different sizes
  -->

<IntfImg:Images>

    <IntfImg:Scope IntfImg:Name="System">
        <IntfImg:Scope IntfImg:Name="ImgPacks">
            <IntfImg:Scope IntfImg:Name="Glyfx">
                <IntfImg:Scope IntfImg:Name="Vista">

                    <IntfImg:Scope IntfImg:Name="32x32">
                        <IntfImg:Scope IntfImg:Name="Disabled">
                            <IntfImg:Image IntfImg:Name="arrow_left_32_d.png"/>
                            <IntfImg:Image IntfImg:Name="arrow_right_32_d.png"/>
                            <IntfImg:Image IntfImg:Name="copy_clipboard_32_d.png"/>
                            <IntfImg:Image IntfImg:Name="copy_clipboard_lined_32_d.png"/>
                            <IntfImg:Image IntfImg:Name="copy_to_folder_32_d.png"/>
                            <IntfImg:Image IntfImg:Name="cut_clipboard_32_d.png"/>
                            <IntfImg:Image IntfImg:Name="delete_32_d.png"/>
                            <IntfImg:Image IntfImg:Name="favorites_32_d.png"/>
                            <IntfImg:Image IntfImg:Name="folders_32_d.png"/>
                            <IntfImg:Image IntfImg:Name="folder_closed_32_d.png"/>
                            <IntfImg:Image IntfImg:Name="folder_open_32_d.png"/>
                            <IntfImg:Image IntfImg:Name="folder_options_32_d.png"/>
                            <IntfImg:Image IntfImg:Name="folder_options_b_32_d.png"/>
                            <IntfImg:Image IntfImg:Name="history_1_32_d.png"/>
                            <IntfImg:Image IntfImg:Name="history_32_d.png"/>
                            <IntfImg:Image IntfImg:Name="history_b1_32_d.png"/>
                            <IntfImg:Image IntfImg:Name="history_b_32_d.png"/>
                            <IntfImg:Image IntfImg:Name="home_32_d.png"/>
                            <IntfImg:Image IntfImg:Name="mail_32_d.png"/>
                            <IntfImg:Image IntfImg:Name="mail_b_32_d.png"/>
                            <IntfImg:Image IntfImg:Name="move_to_folder_32_d.png"/>
                            <IntfImg:Image IntfImg:Name="new_document_32_d.png"/>
                            <IntfImg:Image IntfImg:Name="new_document_lined_32_d.png"/>
                            <IntfImg:Image IntfImg:Name="open_document_32_d.png"/>
                            <IntfImg:Image IntfImg:Name="paste_clipboard_32_d.png"/>
                            <IntfImg:Image IntfImg:Name="paste_clipboard_lined_32_d.png"/>
                            <IntfImg:Image IntfImg:Name="print_32_d.png"/>
                            <IntfImg:Image IntfImg:Name="print_preview_32_d.png"/>
                            <IntfImg:Image IntfImg:Name="print_preview_lined_32_d.png"/>
                            <IntfImg:Image IntfImg:Name="properties_document_32_d.png"/>
                            <IntfImg:Image IntfImg:Name="properties_document_b_32_d.png"/>
                            <IntfImg:Image IntfImg:Name="properties_document_b_lined_32_d.png"/>
                            <IntfImg:Image IntfImg:Name="properties_document_lined_32_d.png"/>
                            <IntfImg:Image IntfImg:Name="redo_32_d.png"/>
                            <IntfImg:Image IntfImg:Name="redo_square_32_d.png"/>
                            <IntfImg:Image IntfImg:Name="refresh_document_32_d.png"/>
                            <IntfImg:Image IntfImg:Name="save_32_d.png"/>
                            <IntfImg:Image IntfImg:Name="search_32_d.png"/>
                            <IntfImg:Image IntfImg:Name="stop_32_d.png"/>
                            <IntfImg:Image IntfImg:Name="undo_32_d.png"/>
                            <IntfImg:Image IntfImg:Name="undo_square_32_d.png"/>
                            <IntfImg:Image IntfImg:Name="up_folder_32_d.png"/>
                            <IntfImg:Image IntfImg:Name="view_32_d.png"/>
                        </IntfImg:Scope>

                        <IntfImg:Scope IntfImg:Name="Hot">
                            <IntfImg:Image IntfImg:Name="arrow_left_32_h.png"/>
                            <IntfImg:Image IntfImg:Name="arrow_right_32_h.png"/>
                            <IntfImg:Image IntfImg:Name="copy_clipboard_32_h.png"/>
                            <IntfImg:Image IntfImg:Name="copy_clipboard_lined_32_h.png"/>
                            <IntfImg:Image IntfImg:Name="copy_to_folder_32_h.png"/>
                            <IntfImg:Image IntfImg:Name="cut_clipboard_32_h.png"/>
                            <IntfImg:Image IntfImg:Name="delete_32_h.png"/>
                            <IntfImg:Image IntfImg:Name="favorites_32_h.png"/>
                            <IntfImg:Image IntfImg:Name="folders_32_h.png"/>
                            <IntfImg:Image IntfImg:Name="folder_closed_32_h.png"/>
                            <IntfImg:Image IntfImg:Name="folder_open_32_h.png"/>
                            <IntfImg:Image IntfImg:Name="folder_options_32_h.png"/>
                            <IntfImg:Image IntfImg:Name="folder_options_b_32_h.png"/>
                            <IntfImg:Image IntfImg:Name="history_1_32_h.png"/>
                            <IntfImg:Image IntfImg:Name="history_32_h.png"/>
                            <IntfImg:Image IntfImg:Name="history_b1_32_h.png"/>
                            <IntfImg:Image IntfImg:Name="history_b_32_h.png"/>
                            <IntfImg:Image IntfImg:Name="home_32_h.png"/>
                            <IntfImg:Image IntfImg:Name="mail_32_h.png"/>
                            <IntfImg:Image IntfImg:Name="mail_b_32_h.png"/>
                            <IntfImg:Image IntfImg:Name="move_to_folder_32_h.png"/>
                            <IntfImg:Image IntfImg:Name="new_document_32_h.png"/>
                            <IntfImg:Image IntfImg:Name="new_document_lined_32_h.png"/>
                            <IntfImg:Image IntfImg:Name="open_document_32_h.png"/>
                            <IntfImg:Image IntfImg:Name="paste_clipboard_32_h.png"/>
                            <IntfImg:Image IntfImg:Name="paste_clipboard_lined_32_h.png"/>
                            <IntfImg:Image IntfImg:Name="print_32_h.png"/>
                            <IntfImg:Image IntfImg:Name="print_preview_32_h.png"/>
                            <IntfImg:Image IntfImg:Name="print_preview_lined_32_h.png"/>
                            <IntfImg:Image IntfImg:Name="properties_document_32_h.png"/>
                            <IntfImg:Image IntfImg:Name="properties_document_b_32_h.png"/>
                            <IntfImg:Image IntfImg:Name="properties_document_b_lined_32_h.png"/>
                            <IntfImg:Image IntfImg:Name="properties_document_lined_32_h.png"/>
                            <IntfImg:Image IntfImg:Name="redo_32_h.png"/>
                            <IntfImg:Image IntfImg:Name="redo_square_32_h.png"/>
                            <IntfImg:Image IntfImg:Name="refresh_document_32_h.png"/>
                            <IntfImg:Image IntfImg:Name="save_32_h.png"/>
                            <IntfImg:Image IntfImg:Name="search_32_h.png"/>
                            <IntfImg:Image IntfImg:Name="stop_32_h.png"/>
                            <IntfImg:Image IntfImg:Name="undo_32_h.png"/>
                            <IntfImg:Image IntfImg:Name="undo_square_32_h.png"/>
                            <IntfImg:Image IntfImg:Name="up_folder_32_h.png"/>
                            <IntfImg:Image IntfImg:Name="view_32_h.png"/>
                        </IntfImg:Scope>

                        <IntfImg:Scope IntfImg:Name="Normal">
                            <IntfImg:Image IntfImg:Name="arrow_left_32.png"/>
                            <IntfImg:Image IntfImg:Name="arrow_right_32.png"/>
                            <IntfImg:Image IntfImg:Name="copy_clipboard_32.png"/>
                            <IntfImg:Image IntfImg:Name="copy_clipboard_lined_32.png"/>
                            <IntfImg:Image IntfImg:Name="copy_to_folder_32.png"/>
                            <IntfImg:Image IntfImg:Name="cut_clipboard_32.png"/>
                            <IntfImg:Image IntfImg:Name="delete_32.png"/>
                            <IntfImg:Image IntfImg:Name="favorites_32.png"/>
                            <IntfImg:Image IntfImg:Name="folders_32.png"/>
                            <IntfImg:Image IntfImg:Name="folder_closed_32.png"/>
                            <IntfImg:Image IntfImg:Name="folder_open_32.png"/>
                            <IntfImg:Image IntfImg:Name="folder_options_32.png"/>
                            <IntfImg:Image IntfImg:Name="folder_options_b_32.png"/>
                            <IntfImg:Image IntfImg:Name="history_1_32.png"/>
                            <IntfImg:Image IntfImg:Name="history_32.png"/>
                            <IntfImg:Image IntfImg:Name="history_b1_32.png"/>
                            <IntfImg:Image IntfImg:Name="history_b_32.png"/>
                            <IntfImg:Image IntfImg:Name="home_32.png"/>
                            <IntfImg:Image IntfImg:Name="mail_32.png"/>
                            <IntfImg:Image IntfImg:Name="mail_b_32.png"/>
                            <IntfImg:Image IntfImg:Name="move_to_folder_32.png"/>
                            <IntfImg:Image IntfImg:Name="new_document_32.png"/>
                            <IntfImg:Image IntfImg:Name="new_document_lined_32.png"/>
                            <IntfImg:Image IntfImg:Name="open_document_32.png"/>
                            <IntfImg:Image IntfImg:Name="paste_clipboard_32.png"/>
                            <IntfImg:Image IntfImg:Name="paste_clipboard_lined_32.png"/>
                            <IntfImg:Image IntfImg:Name="print_32.png"/>
                            <IntfImg:Image IntfImg:Name="print_preview_32.png"/>
                            <IntfImg:Image IntfImg:Name="print_preview_lined_32.png"/>
                            <IntfImg:Image IntfImg:Name="properties_document_32.png"/>
                            <IntfImg:Image IntfImg:Name="properties_document_b_32.png"/>
                            <IntfImg:Image IntfImg:Name="properties_document_b_lined_32.png"/>
                            <IntfImg:Image IntfImg:Name="properties_document_lined_32.png"/>
                            <IntfImg:Image IntfImg:Name="redo_32.png"/>
                            <IntfImg:Image IntfImg:Name="redo_square_32.png"/>
                            <IntfImg:Image IntfImg:Name="refresh_document_32.png"/>
                            <IntfImg:Image IntfImg:Name="save_32.png"/>
                            <IntfImg:Image IntfImg:Name="search_32.png"/>
                            <IntfImg:Image IntfImg:Name="stop_32.png"/>
                            <IntfImg:Image IntfImg:Name="undo_32.png"/>
                            <IntfImg:Image IntfImg:Name="undo_square_32.png"/>
                            <IntfImg:Image IntfImg:Name="up_folder_32.png"/>
                            <IntfImg:Image IntfImg:Name="view_32.png"/>
                        </IntfImg:Scope>
                    </IntfImg:Scope>

                    <IntfImg:Scope IntfImg:Name="48x48">
                        <IntfImg:Scope IntfImg:Name="Disabled">
                            <IntfImg:Image IntfImg:Name="arrow_left_48_d.png"/>
                            <IntfImg:Image IntfImg:Name="arrow_right_48_d.png"/>
                            <IntfImg:Image IntfImg:Name="copy_clipboard_48_d.png"/>
                            <IntfImg:Image IntfImg:Name="copy_clipboard_lined_48_d.png"/>
                            <IntfImg:Image IntfImg:Name="copy_to_folder_48_d.png"/>
                            <IntfImg:Image IntfImg:Name="cut_clipboard_48_d.png"/>
                            <IntfImg:Image IntfImg:Name="delete_48_d.png"/>
                            <IntfImg:Image IntfImg:Name="favorites_48_d.png"/>
                            <IntfImg:Image IntfImg:Name="folders_48_d.png"/>
                            <IntfImg:Image IntfImg:Name="folder_closed_48_d.png"/>
                            <IntfImg:Image IntfImg:Name="folder_open_48_d.png"/>
                            <IntfImg:Image IntfImg:Name="folder_options_48_d.png"/>
                            <IntfImg:Image IntfImg:Name="folder_options_b_48_d.png"/>
                            <IntfImg:Image IntfImg:Name="history_1_48_d.png"/>
                            <IntfImg:Image IntfImg:Name="history_48_d.png"/>
                            <IntfImg:Image IntfImg:Name="history_b1_48_d.png"/>
                            <IntfImg:Image IntfImg:Name="history_b_48_d.png"/>
                            <IntfImg:Image IntfImg:Name="home_48_d.png"/>
                            <IntfImg:Image IntfImg:Name="mail_48_d.png"/>
                            <IntfImg:Image IntfImg:Name="mail_b_48_d.png"/>
                            <IntfImg:Image IntfImg:Name="move_to_folder_48_d.png"/>
                            <IntfImg:Image IntfImg:Name="new_document_48_d.png"/>
                            <IntfImg:Image IntfImg:Name="new_document_lined_48_d.png"/>
                            <IntfImg:Image IntfImg:Name="open_document_48_d.png"/>
                            <IntfImg:Image IntfImg:Name="paste_clipboard_48_d.png"/>
                            <IntfImg:Image IntfImg:Name="paste_clipboard_lined_48_d.png"/>
                            <IntfImg:Image IntfImg:Name="print_48_d.png"/>
                            <IntfImg:Image IntfImg:Name="print_preview_48_d.png"/>
                            <IntfImg:Image IntfImg:Name="print_preview_lined_48_d.png"/>
                            <IntfImg:Image IntfImg:Name="properties_document_48_d.png"/>
                            <IntfImg:Image IntfImg:Name="properties_document_b_48_d.png"/>
                            <IntfImg:Image IntfImg:Name="properties_document_b_lined_48_d.png"/>
                            <IntfImg:Image IntfImg:Name="properties_document_lined_48_d.png"/>
                            <IntfImg:Image IntfImg:Name="redo_48_d.png"/>
                            <IntfImg:Image IntfImg:Name="redo_square_48_d.png"/>
                            <IntfImg:Image IntfImg:Name="refresh_document_48_d.png"/>
                            <IntfImg:Image IntfImg:Name="save_48_d.png"/>
                            <IntfImg:Image IntfImg:Name="search_48_d.png"/>
                            <IntfImg:Image IntfImg:Name="stop_48_d.png"/>
                            <IntfImg:Image IntfImg:Name="undo_48_d.png"/>
                            <IntfImg:Image IntfImg:Name="undo_square_48_d.png"/>
                            <IntfImg:Image IntfImg:Name="up_folder_48_d.png"/>
                            <IntfImg:Image IntfImg:Name="view_48_d.png"/>
                        </IntfImg:Scope>

                        <IntfImg:Scope IntfImg:Name="Hot">
                            <IntfImg:Image IntfImg:Name="arrow_left_48_h.png"/>
                            <IntfImg:Image IntfImg:Name="arrow_right_48_h.png"/>
                            <IntfImg:Image IntfImg:Name="copy_clipboard_48_h.png"/>
                            <IntfImg:Image IntfImg:Name="copy_clipboard_lined_48_h.png"/>
                            <IntfImg:Image IntfImg:Name="copy_to_folder_48_h.png"/>
                            <IntfImg:Image IntfImg:Name="cut_clipboard_48_h.png"/>
                            <IntfImg:Image IntfImg:Name="delete_48_h.png"/>
                            <IntfImg:Image IntfImg:Name="favorites_48_h.png"/>
                            <IntfImg:Image IntfImg:Name="folders_48_h.png"/>
                            <IntfImg:Image IntfImg:Name="folder_closed_48_h.png"/>
                            <IntfImg:Image IntfImg:Name="folder_open_48_h.png"/>
                            <IntfImg:Image IntfImg:Name="folder_options_48_h.png"/>
                            <IntfImg:Image IntfImg:Name="folder_options_b_48_h.png"/>
                            <IntfImg:Image IntfImg:Name="history_1_48_h.png"/>
                            <IntfImg:Image IntfImg:Name="history_48_h.png"/>
                            <IntfImg:Image IntfImg:Name="history_b1_48_h.png"/>
                            <IntfImg:Image IntfImg:Name="history_b_48_h.png"/>
                            <IntfImg:Image IntfImg:Name="home_48_h.png"/>
                            <IntfImg:Image IntfImg:Name="mail_48_h.png"/>
                            <IntfImg:Image IntfImg:Name="mail_b_48_h.png"/>
                            <IntfImg:Image IntfImg:Name="move_to_folder_48_h.png"/>
                            <IntfImg:Image IntfImg:Name="new_document_48_h.png"/>
                            <IntfImg:Image IntfImg:Name="new_document_lined_48_h.png"/>
                            <IntfImg:Image IntfImg:Name="open_document_48_h.png"/>
                            <IntfImg:Image IntfImg:Name="paste_clipboard_48_h.png"/>
                            <IntfImg:Image IntfImg:Name="paste_clipboard_lined_48_h.png"/>
                            <IntfImg:Image IntfImg:Name="print_48_h.png"/>
                            <IntfImg:Image IntfImg:Name="print_preview_48_h.png"/>
                            <IntfImg:Image IntfImg:Name="print_preview_lined_48_h.png"/>
                            <IntfImg:Image IntfImg:Name="properties_document_48_h.png"/>
                            <IntfImg:Image IntfImg:Name="properties_document_b_48_h.png"/>
                            <IntfImg:Image IntfImg:Name="properties_document_b_lined_48_h.png"/>
                            <IntfImg:Image IntfImg:Name="properties_document_lined_48_h.png"/>
                            <IntfImg:Image IntfImg:Name="redo_48_h.png"/>
                            <IntfImg:Image IntfImg:Name="redo_square_48_h.png"/>
                            <IntfImg:Image IntfImg:Name="refresh_document_48_h.png"/>
                            <IntfImg:Image IntfImg:Name="save_48_h.png"/>
                            <IntfImg:Image IntfImg:Name="search_48_h.png"/>
                            <IntfImg:Image IntfImg:Name="stop_48_h.png"/>
                            <IntfImg:Image IntfImg:Name="undo_48_h.png"/>
                            <IntfImg:Image IntfImg:Name="undo_square_48_h.png"/>
                            <IntfImg:Image IntfImg:Name="up_folder_48_h.png"/>
                            <IntfImg:Image IntfImg:Name="view_48_h.png"/>
                        </IntfImg:Scope>

                        <IntfImg:Scope IntfImg:Name="Normal">
                            <IntfImg:Image IntfImg:Name="arrow_left_48.png"/>
                            <IntfImg:Image IntfImg:Name="arrow_right_48.png"/>
                            <IntfImg:Image IntfImg:Name="copy_clipboard_48.png"/>
                            <IntfImg:Image IntfImg:Name="copy_clipboard_lined_48.png"/>
                            <IntfImg:Image IntfImg:Name="copy_to_folder_48.png"/>
                            <IntfImg:Image IntfImg:Name="cut_clipboard_48.png"/>
                            <IntfImg:Image IntfImg:Name="delete_48.png"/>
                            <IntfImg:Image IntfImg:Name="favorites_48.png"/>
                            <IntfImg:Image IntfImg:Name="folders_48.png"/>
                            <IntfImg:Image IntfImg:Name="folder_closed_48.png"/>
                            <IntfImg:Image IntfImg:Name="folder_open_48.png"/>
                            <IntfImg:Image IntfImg:Name="folder_options_48.png"/>
                            <IntfImg:Image IntfImg:Name="folder_options_b_48.png"/>
                            <IntfImg:Image IntfImg:Name="history_1_48.png"/>
                            <IntfImg:Image IntfImg:Name="history_48.png"/>
                            <IntfImg:Image IntfImg:Name="history_b1_48.png"/>
                            <IntfImg:Image IntfImg:Name="history_b_48.png"/>
                            <IntfImg:Image IntfImg:Name="home_48.png"/>
                            <IntfImg:Image IntfImg:Name="mail_48.png"/>
                            <IntfImg:Image IntfImg:Name="mail_b_48.png"/>
                            <IntfImg:Image IntfImg:Name="move_to_folder_48.png"/>
                            <IntfImg:Image IntfImg:Name="new_document_48.png"/>
                            <IntfImg:Image IntfImg:Name="new_document_lined_48.png"/>
                            <IntfImg:Image IntfImg:Name="open_document_48.png"/>
                            <IntfImg:Image IntfImg:Name="paste_clipboard_48.png"/>
                            <IntfImg:Image IntfImg:Name="paste_clipboard_lined_48.png"/>
                            <IntfImg:Image IntfImg:Name="print_48.png"/>
                            <IntfImg:Image IntfImg:Name="print_preview_48.png"/>
                            <IntfImg:Image IntfImg:Name="print_preview_lined_48.png"/>
                            <IntfImg:Image IntfImg:Name="properties_document_48.png"/>
                            <IntfImg:Image IntfImg:Name="properties_document_b_48.png"/>
                            <IntfImg:Image IntfImg:Name="properties_document_lined_48.png"/>
                            <IntfImg:Image IntfImg:Name="properties_document_lined_b_48.png"/>
                            <IntfImg:Image IntfImg:Name="redo_48.png"/>
                            <IntfImg:Image IntfImg:Name="redo_square_48.png"/>
                            <IntfImg:Image IntfImg:Name="refresh_document_48.png"/>
                            <IntfImg:Image IntfImg:Name="save_48.png"/>
                            <IntfImg:Image IntfImg:Name="search_48.png"/>
                            <IntfImg:Image IntfImg:Name="stop_48.png"/>
                            <IntfImg:Image IntfImg:Name="undo_48.png"/>
                            <IntfImg:Image IntfImg:Name="undo_square_48.png"/>
                            <IntfImg:Image IntfImg:Name="up_folder_48.png"/>
                            <IntfImg:Image IntfImg:Name="view_48.png"/>
                        </IntfImg:Scope>
                    </IntfImg:Scope>

                    <IntfImg:Scope IntfImg:Name="64x64">
                        <IntfImg:Scope IntfImg:Name="Disabled">
                            <IntfImg:Image IntfImg:Name="arrow_left_64_d.png"/>
                            <IntfImg:Image IntfImg:Name="arrow_right_64_d.png"/>
                            <IntfImg:Image IntfImg:Name="copy_clipboard_64_d.png"/>
                            <IntfImg:Image IntfImg:Name="copy_clipboard_lined_64_d.png"/>
                            <IntfImg:Image IntfImg:Name="copy_to_folder_64_d.png"/>
                            <IntfImg:Image IntfImg:Name="cut_clipboard_64_d.png"/>
                            <IntfImg:Image IntfImg:Name="delete_64_d.png"/>
                            <IntfImg:Image IntfImg:Name="favorites_64_d.png"/>
                            <IntfImg:Image IntfImg:Name="folders_64_d.png"/>
                            <IntfImg:Image IntfImg:Name="folder_closed_64_d.png"/>
                            <IntfImg:Image IntfImg:Name="folder_open_64_d.png"/>
                            <IntfImg:Image IntfImg:Name="folder_options_64_d.png"/>
                            <IntfImg:Image IntfImg:Name="folder_options_b_64_d.png"/>
                            <IntfImg:Image IntfImg:Name="history_1_64_d.png"/>
                            <IntfImg:Image IntfImg:Name="history_64_d.png"/>
                            <IntfImg:Image IntfImg:Name="history_b1_64_d.png"/>
                            <IntfImg:Image IntfImg:Name="history_b_64_d.png"/>
                            <IntfImg:Image IntfImg:Name="home_64_d.png"/>
                            <IntfImg:Image IntfImg:Name="mail_64_d.png"/>
                            <IntfImg:Image IntfImg:Name="mail_b_64_d.png"/>
                            <IntfImg:Image IntfImg:Name="move_to_folder_64_d.png"/>
                            <IntfImg:Image IntfImg:Name="new_document_64_d.png"/>
                            <IntfImg:Image IntfImg:Name="new_document_lined_64_d.png"/>
                            <IntfImg:Image IntfImg:Name="open_document_64_d.png"/>
                            <IntfImg:Image IntfImg:Name="paste_clipboard_64_d.png"/>
                            <IntfImg:Image IntfImg:Name="paste_clipboard_lined_64_d.png"/>
                            <IntfImg:Image IntfImg:Name="print_64_d.png"/>
                            <IntfImg:Image IntfImg:Name="print_preview_64_d.png"/>
                            <IntfImg:Image IntfImg:Name="print_preview_lined_64_d.png"/>
                            <IntfImg:Image IntfImg:Name="properties_document_64_d.png"/>
                            <IntfImg:Image IntfImg:Name="properties_document_b_64_d.png"/>
                            <IntfImg:Image IntfImg:Name="properties_document_b_lined_64_d.png"/>
                            <IntfImg:Image IntfImg:Name="properties_document_lined_64_d.png"/>
                            <IntfImg:Image IntfImg:Name="redo_64_d.png"/>
                            <IntfImg:Image IntfImg:Name="redo_square_64_d.png"/>
                            <IntfImg:Image IntfImg:Name="refresh_document_64_d.png"/>
                            <IntfImg:Image IntfImg:Name="save_64_d.png"/>
                            <IntfImg:Image IntfImg:Name="search_64_d.png"/>
                            <IntfImg:Image IntfImg:Name="stop_64_d.png"/>
                            <IntfImg:Image IntfImg:Name="undo_64_d.png"/>
                            <IntfImg:Image IntfImg:Name="undo_square_64_d.png"/>
                            <IntfImg:Image IntfImg:Name="up_folder_64_d.png"/>
                            <IntfImg:Image IntfImg:Name="view_64_d.png"/>
                        </IntfImg:Scope>

                        <IntfImg:Scope IntfImg:Name="Hot">
                            <IntfImg:Image IntfImg:Name="arrow_left_64_h.png"/>
                            <IntfImg:Image IntfImg:Name="arrow_right_64_h.png"/>
                            <IntfImg:Image IntfImg:Name="copy_clipboard_64_h.png"/>
                            <IntfImg:Image IntfImg:Name="copy_clipboard_lined_64_h.png"/>
                            <IntfImg:Image IntfImg:Name="copy_to_folder_64_h.png"/>
                            <IntfImg:Image IntfImg:Name="cut_clipboard_64_h.png"/>
                            <IntfImg:Image IntfImg:Name="delete_64_h.png"/>
                            <IntfImg:Image IntfImg:Name="favorites_64_h.png"/>
                            <IntfImg:Image IntfImg:Name="folders_64_h.png"/>
                            <IntfImg:Image IntfImg:Name="folder_closed_64_h.png"/>
                            <IntfImg:Image IntfImg:Name="folder_open_64_h.png"/>
                            <IntfImg:Image IntfImg:Name="folder_options_64_h.png"/>
                            <IntfImg:Image IntfImg:Name="folder_options_b_64_h.png"/>
                            <IntfImg:Image IntfImg:Name="history_1_64_h.png"/>
                            <IntfImg:Image IntfImg:Name="history_64_h.png"/>
                            <IntfImg:Image IntfImg:Name="history_b1_64_h.png"/>
                            <IntfImg:Image IntfImg:Name="history_b_64_h.png"/>
                            <IntfImg:Image IntfImg:Name="home_64_h.png"/>
                            <IntfImg:Image IntfImg:Name="mail_64_h.png"/>
                            <IntfImg:Image IntfImg:Name="mail_b_64_h.png"/>
                            <IntfImg:Image IntfImg:Name="move_to_folder_64_h.png"/>
                            <IntfImg:Image IntfImg:Name="new_document_64_h.png"/>
                            <IntfImg:Image IntfImg:Name="new_document_lined_64_h.png"/>
                            <IntfImg:Image IntfImg:Name="open_document_64_h.png"/>
                            <IntfImg:Image IntfImg:Name="paste_clipboard_64_h.png"/>
                            <IntfImg:Image IntfImg:Name="paste_clipboard_lined_64_h.png"/>
                            <IntfImg:Image IntfImg:Name="print_64_h.png"/>
                            <IntfImg:Image IntfImg:Name="print_preview_64_h.png"/>
                            <IntfImg:Image IntfImg:Name="print_preview_lined_64_h.png"/>
                            <IntfImg:Image IntfImg:Name="properties_document_64_h.png"/>
                            <IntfImg:Image IntfImg:Name="properties_document_b_64_h.png"/>
                            <IntfImg:Image IntfImg:Name="properties_document_b_lined_64_h.png"/>
                            <IntfImg:Image IntfImg:Name="properties_document_lined_64_h.png"/>
                            <IntfImg:Image IntfImg:Name="redo_64_h.png"/>
                            <IntfImg:Image IntfImg:Name="redo_square_64_h.png"/>
                            <IntfImg:Image IntfImg:Name="refresh_document_64_h.png"/>
                            <IntfImg:Image IntfImg:Name="save_64_h.png"/>
                            <IntfImg:Image IntfImg:Name="search_64_h.png"/>
                            <IntfImg:Image IntfImg:Name="stop_64_h.png"/>
                            <IntfImg:Image IntfImg:Name="undo_64_h.png"/>
                            <IntfImg:Image IntfImg:Name="undo_square_64_h.png"/>
                            <IntfImg:Image IntfImg:Name="up_folder_64_h.png"/>
                            <IntfImg:Image IntfImg:Name="view_64_h.png"/>
                        </IntfImg:Scope>

                        <IntfImg:Scope IntfImg:Name="Normal">