<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE IntfImg:Images
[
    <!ELEMENT IntfImg:Image  EMPTY>
    <!ATTLIST IntfImg:Image  IntfImg:Name CDATA #REQUIRED
                             IntfImg:Trans (Yes | No) "No"
                             IntfImg:TransAt CDATA "0,0">
    <!ELEMENT IntfImg:Scope  (IntfImg:Scope | IntfImg:Image)*>
    <!ATTLIST IntfImg:Scope  IntfImg:Name CDATA #REQUIRED>
    <!ELEMENT IntfImg:Images (IntfImg:Scope+)>
]>

<IntfImg:Images>

    <IntfImg:Scope IntfImg:Name="System">
        <IntfImg:Scope IntfImg:Name="ImgPacks">
            <IntfImg:Scope IntfImg:Name="Logos">
                <IntfImg:Scope IntfImg:Name="DirecTV">
                    <IntfImg:Image IntfImg:Name="202.png"/>
                    <IntfImg:Image IntfImg:Name="203.png"/>
                    <IntfImg:Image IntfImg:Name="204.png"/>
                    <IntfImg:Image IntfImg:Name="206.png"/>
                    <IntfImg:Image IntfImg:Name="207.png"/>
                    <IntfImg:Image IntfImg:Name="208.png"/>
                    <IntfImg:Image IntfImg:Name="209.png"/>
                    <IntfImg:Image IntfImg:Name="213.png"/>
                    <IntfImg:Image IntfImg:Name="224.png"/>
                    <IntfImg:Image IntfImg:Name="229.png"/>
                    <IntfImg:Image IntfImg:Name="230.png"/>
                    <IntfImg:Image IntfImg:Name="231.png"/>
                    <IntfImg:Image IntfImg:Name="232.png"/>
                    <IntfImg:Image IntfImg:Name="236.png"/>
                    <IntfImg:Image IntfImg:Name="240.png"/>
                    <IntfImg:Image IntfImg:Name="242.png"/>
                    <IntfImg:Image IntfImg:Name="244.png"/>
                    <IntfImg:Image IntfImg:Name="245.png"/>
                    <IntfImg:Image IntfImg:Name="247.png"/>
                    <IntfImg:Image IntfImg:Name="248.png"/>
                    <IntfImg:Image IntfImg:Name="249.png"/>
                    <IntfImg:Image IntfImg:Name="252.png"/>
                    <IntfImg:Image IntfImg:Name="253.png"/>
                    <IntfImg:Image IntfImg:Name="254.png"/>
                    <IntfImg:Image IntfImg:Name="256.png"/>
                    <IntfImg:Image IntfImg:Name="258.png"/>
                    <IntfImg:Image IntfImg:Name="260.png"/>
                    <IntfImg:Image IntfImg:Name="262.png"/>
                    <IntfImg:Image IntfImg:Name="264.png"/>
                    <IntfImg:Image IntfImg:Name="266.png"/>
                    <IntfImg:Image IntfImg:Name="269.png"/>
                    <IntfImg:Image IntfImg:Name="273.png"/>
                    <IntfImg:Image IntfImg:Name="276.png"/>
                    <IntfImg:Image IntfImg:Name="278.png"/>
                    <IntfImg:Image IntfImg:Name="280.png"/>
                    <IntfImg:Image IntfImg:Name="282.png"/>
                    <IntfImg:Image IntfImg:Name="290.png"/>
                    <IntfImg:Image IntfImg:Name="295.png"/>
                    <IntfImg:Image IntfImg:Name="296.png"/>
                    <IntfImg:Image IntfImg:Name="297.png"/>
                    <IntfImg:Image IntfImg:Name="298.png"/>
                    <IntfImg:Image IntfImg:Name="299.png"/>
                    <IntfImg:Image IntfImg:Name="301.png"/>
                    <IntfImg:Image IntfImg:Name="307.png"/>
                    <IntfImg:Image IntfImg:Name="309.png"/>
                    <IntfImg:Image IntfImg:Name="311.png"/>
                    <IntfImg:Image IntfImg:Name="312.png"/>
                    <IntfImg:Image IntfImg:Name="317.png"/>
                    <IntfImg:Image IntfImg:Name="325.png"/>
                    <IntfImg:Image IntfImg:Name="327.png"/>
                    <IntfImg:Image IntfImg:Name="329.png"/>
                    <IntfImg:Image IntfImg:Name="331.png"/>
                    <IntfImg:Image IntfImg:Name="335.png"/>
                    <IntfImg:Image IntfImg:Name="337.png"/>
                    <IntfImg:Image IntfImg:Name="350.png"/>
                    <IntfImg:Image IntfImg:Name="351.png"/>
                    <IntfImg:Image IntfImg:Name="353.png"/>
                    <IntfImg:Image IntfImg:Name="355.png"/>
                    <IntfImg:Image IntfImg:Name="357.png"/>
                    <IntfImg:Image IntfImg:Name="362.png"/>
                    <IntfImg:Image IntfImg:Name="370.png"/>
                    <IntfImg:Image IntfImg:Name="372.png"/>
                    <IntfImg:Image IntfImg:Name="376.png"/>
                    <IntfImg:Image IntfImg:Name="384.png"/>
                    <IntfImg:Image IntfImg:Name="388.png"/>
                    <IntfImg:Image IntfImg:Name="402.png"/>
                    <IntfImg:Image IntfImg:Name="404.png"/>
                    <IntfImg:Image IntfImg:Name="422.png"/>
                    <IntfImg:Image IntfImg:Name="441.png"/>
                    <IntfImg:Image IntfImg:Name="442.png"/>
                    <IntfImg:Image IntfImg:Name="501.png"/>
                    <IntfImg:Image IntfImg:Name="512.png"/>
                    <IntfImg:Image IntfImg:Name="520.png"/>
                    <IntfImg:Image IntfImg:Name="526.png"/>
                    <IntfImg:Image IntfImg:Name="527.png"/>
                    <IntfImg:Image IntfImg:Name="537.png"/>
                    <IntfImg:Image IntfImg:Name="547.png"/>
                    <IntfImg:Image IntfImg:Name="550.png"/>
                    <IntfImg:Image IntfImg:Name="76.png"/>
                    <IntfImg:Image IntfImg:Name="78.png"/>
                    <IntfImg:Image IntfImg:Name="79.png"/>
                    <IntfImg:Image IntfImg:Name="88.png"/>
                    <IntfImg:Image IntfImg:Name="91.png"/>

                    <IntfImg:Scope IntfImg:Name="Trans">
                        <IntfImg:Image IntfImg:Name="202.png"/>
                        <IntfImg:Image IntfImg:Name="203.png"/>
                        <IntfImg:Image IntfImg:Name="204.png"/>
                        <IntfImg:Image IntfImg:Name="206.png"/>
                        <IntfImg:Image IntfImg:Name="207.png"/>
                        <IntfImg:Image IntfImg:Name="208.png"/>
                        <IntfImg:Image IntfImg:Name="209.png"/>
                        <IntfImg:Image IntfImg:Name="213.png"/>
                        <IntfImg:Image IntfImg:Name="224.png"/>
                        <IntfImg:Image IntfImg:Name="229.png"/>
                        <IntfImg:Image IntfImg:Name="230.png"/>
                        <IntfImg:Image IntfImg:Name="231.png"/>
                        <IntfImg:Image IntfImg:Name="232.png"/>
                        <IntfImg:Image IntfImg:Name="236.png"/>
                        <IntfImg:Image IntfImg:Name="240.png"/>
                        <IntfImg:Image IntfImg:Name="242.png"/>
                        <IntfImg:Image IntfImg:Name="244.png"/>
                        <IntfImg:Image IntfImg:Name="245.png"/>
                        <IntfImg:Image IntfImg:Name="247.png"/>
                        <IntfImg:Image IntfImg:Name="248.png"/>
                        <IntfImg:Image IntfImg:Name="249.png"/>
                        <IntfImg:Image IntfImg:Name="252.png"/>
                        <IntfImg:Image IntfImg:Name="253.png"/>
                        <IntfImg:Image IntfImg:Name="254.png"/>
                        <IntfImg:Image IntfImg:Name="256.png"/>
                        <IntfImg:Image IntfImg:Name="258.png"/>
                        <IntfImg:Image IntfImg:Name="260.png"/>
                        <IntfImg:Image IntfImg:Name="262.png"/>
                        <IntfImg:Image IntfImg:Name="264.png"/>
                        <IntfImg:Image IntfImg:Name="266.png"/>
                        <IntfImg:Image IntfImg:Name="269.png"/>
                        <IntfImg:Image IntfImg:Name="273.png"/>
                        <IntfImg:Image IntfImg:Name="276.png"/>
                        <IntfImg:Image IntfImg:Name="278.png"/>
                        <IntfImg:Image IntfImg:Name="280.png"/>
                        <IntfImg:Image IntfImg:Name="282.png"/>
                        <IntfImg:Image IntfImg:Name="290.png"/>
                        <IntfImg:Image IntfImg:Name="295.png"/>
                        <IntfImg:Image IntfImg:Name="296.png"/>
                        <IntfImg:Image IntfImg:Name="297.png"/>
                        <IntfImg:Image IntfImg:Name="298.png"/>
                        <IntfImg:Image IntfImg:Name="299.png"/>
                        <IntfImg:Image IntfImg:Name="301.png"/>
                        <IntfImg:Image IntfImg:Name="307.png"/>
                        <IntfImg:Image IntfImg:Name="309.png"/>
                        <IntfImg:Image IntfImg:Name="311.png"/>
                        <IntfImg:Image IntfImg:Name="312.png"/>
                        <IntfImg:Image IntfImg:Name="317.png"/>
                        <IntfImg:Image IntfImg:Name="325.png"/>
                        <IntfImg:Image IntfImg:Name="327.png"/>
                        <IntfImg:Image IntfImg:Name="329.png"/>
                        <IntfImg:Image IntfImg:Name="331.png"/>
                        <IntfImg:Image IntfImg:Name="335.png"/>
                        <IntfImg:Image IntfImg:Name="337.png"/>
                        <IntfImg:Image IntfImg:Name="350.png"/>
                        <IntfImg:Image IntfImg:Name="351.png"/>
                        <IntfImg:Image IntfImg:Name="353.png"/>
                        <IntfImg:Image IntfImg:Name="355.png"/>
                        <IntfImg:Image IntfImg:Name="357.png"/>
                        <IntfImg:Image IntfImg:Name="362.png"/>
                        <IntfImg:Image IntfImg:Name="370.png"/>
                        <IntfImg:Image IntfImg:Name="372.png"/>
                        <IntfImg:Image IntfImg:Name="376.png"/>
                        <IntfImg:Image IntfImg:Name="384.png"/>
                        <IntfImg:Image IntfImg:Name="388.png"/>
                        <IntfImg:Image IntfImg:Name="402.png"/>
                        <IntfImg:Image IntfImg:Name="404.png"/>
                        <IntfImg:Image IntfImg:Name="422.png"/>
                        <IntfImg:Image IntfImg:Name="441.png"/>
                        <IntfImg:Image IntfImg:Name="442.png"/>
                        <IntfImg:Image IntfImg:Name="501.png"/>
                        <IntfImg:Image IntfImg:Name="512.png"/>
                        <IntfImg:Image IntfImg:Name="520.png"/>
                        <IntfImg:Image IntfImg:Name="526.png"/>
                        <IntfImg:Image IntfImg:Name="527.png"/>
                        <IntfImg:Image IntfImg:Name="537.png"/>
                        <IntfImg:Image IntfImg:Name="547.png"/>
                        <IntfImg:Image IntfImg:Name="550.png"/>
                        <IntfImg:Image IntfImg:Name="76.png"/>
                        <IntfImg:Image IntfImg:Name="78.png"/>
                        <IntfImg:Image IntfImg:Name="79.png"/>
                        <IntfImg:Image IntfImg:Name="88.png"/>
                        <IntfImg:Image IntfImg:Name="91.png"/>
                    </IntfImg:Scope>
                </IntfImg:Scope>
            </IntfImg:Scope>
        </IntfImg:Scope>
    </IntfImg:Scope>
</IntfImg:Images>

