<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE IntfImg:SysImages
[
    <!ELEMENT IntfImg:Image EMPTY>
    <!ATTLIST IntfImg:Image IntfImg:Name CDATA #REQUIRED
                            IntfImg:Trans (Yes | No) "No"
                            IntfImg:TransAt CDATA "0,0">
    <!ELEMENT IntfImg:Scope (IntfImg:Scope | IntfImg:Image)*>
    <!ATTLIST IntfImg:Scope IntfImg:Name CDATA #REQUIRED
                            IntfImg:Prefixes CDATA #IMPLIED>
    <!ELEMENT IntfImg:SysImages (IntfImg:Image | IntfImg:Scope)+>
]>

<IntfImg:SysImages>

    <IntfImg:Image IntfImg:Name="Blank.png"/>

    <!-- All the background fill type images are under here -->
    <IntfImg:Scope IntfImg:Name="Backgrounds">

        <!-- Tiled patterns -->
        <IntfImg:Scope IntfImg:Name="Tiles">
            <IntfImg:Image IntfImg:Name="Abstract Pattern 1.bmp"/>
            <IntfImg:Image IntfImg:Name="Abstract Pattern 2.bmp"/>
            <IntfImg:Image IntfImg:Name="Blue Sky 1.bmp"/>
            <IntfImg:Image IntfImg:Name="Brushed Aluminum.png"/>
            <IntfImg:Image IntfImg:Name="Floral Pattern 1.bmp"/>
            <IntfImg:Image IntfImg:Name="Rough Texture 1.bmp"/>
            <IntfImg:Image IntfImg:Name="Rough Texture 2.bmp"/>
            <IntfImg:Image IntfImg:Name="Rough Texture 3.bmp"/>
            <IntfImg:Image IntfImg:Name="Spiral Notebook.bmp"/>
            <IntfImg:Image IntfImg:Name="Water Drops 1.bmp"/>
        </IntfImg:Scope>
    </IntfImg:Scope>


    <!-- All the standard CQSL button images are under here -->
    <IntfImg:Scope IntfImg:Name="Buttons">

        <IntfImg:Scope IntfImg:Name="Alpha">
            <IntfImg:Image IntfImg:Name="Long Rounded.png"/>
            <IntfImg:Image IntfImg:Name="Long Square 1.png"/>
            <IntfImg:Image IntfImg:Name="Long Square 2.png"/>
            <IntfImg:Image IntfImg:Name="Long Square 3.png"/>
            <IntfImg:Image IntfImg:Name="Long Square 4.png"/>
            <IntfImg:Image IntfImg:Name="Short Square 1.png"/>
            <IntfImg:Image IntfImg:Name="Short Square 2.png"/>
            <IntfImg:Image IntfImg:Name="Short Square 3.png"/>
            <IntfImg:Image IntfImg:Name="Short Square 4.png"/>
        </IntfImg:Scope>

        <IntfImg:Scope IntfImg:Name="Gel">
            <IntfImg:Image IntfImg:Name="Long Blue.png"/>
            <IntfImg:Image IntfImg:Name="Long Cyan.png"/>
            <IntfImg:Image IntfImg:Name="Long Gold.png"/>
            <IntfImg:Image IntfImg:Name="Long Green.png"/>
            <IntfImg:Image IntfImg:Name="Long Light Purple.png"/>
            <IntfImg:Image IntfImg:Name="Long Purple.png"/>
            <IntfImg:Image IntfImg:Name="Long Red.png"/>
            <IntfImg:Image IntfImg:Name="Long Yellow.png"/>
            <IntfImg:Image IntfImg:Name="Long Sunken Surround.png"/>

            <IntfImg:Image IntfImg:Name="Short Blue.png"/>
            <IntfImg:Image IntfImg:Name="Short Cyan.png"/>
            <IntfImg:Image IntfImg:Name="Short Gold.png"/>
            <IntfImg:Image IntfImg:Name="Short Green.png"/>
            <IntfImg:Image IntfImg:Name="Short Light Purple.png"/>
            <IntfImg:Image IntfImg:Name="Short Purple.png"/>
            <IntfImg:Image IntfImg:Name="Short Red.png"/>
            <IntfImg:Image IntfImg:Name="Short Yellow.png"/>
            <IntfImg:Image IntfImg:Name="Long Sunken Surround.png"/>

            <IntfImg:Scope IntfImg:Name="Small">
                <IntfImg:Image IntfImg:Name="Ex Short Blue.png"/>
                <IntfImg:Image IntfImg:Name="Ex Short Cyan.png"/>
                <IntfImg:Image IntfImg:Name="Ex Short Gold.png"/>
                <IntfImg:Image IntfImg:Name="Ex Short Green.png"/>
                <IntfImg:Image IntfImg:Name="Ex Short Light Purple.png"/>
                <IntfImg:Image IntfImg:Name="Ex Short Purple.png"/>
                <IntfImg:Image IntfImg:Name="Ex Short Red.png"/>
                <IntfImg:Image IntfImg:Name="Ex Short Yellow.png"/>
                <IntfImg:Image IntfImg:Name="Ex Short Sunken Surround.png"/>

                <IntfImg:Image IntfImg:Name="Long Blue.png"/>
                <IntfImg:Image IntfImg:Name="Long Cyan.png"/>
                <IntfImg:Image IntfImg:Name="Long Gold.png"/>
                <IntfImg:Image IntfImg:Name="Long Green.png"/>
                <IntfImg:Image IntfImg:Name="Long Light Purple.png"/>
                <IntfImg:Image IntfImg:Name="Long Purple.png"/>
                <IntfImg:Image IntfImg:Name="Long Red.png"/>
                <IntfImg:Image IntfImg:Name="Long Yellow.png"/>
                <IntfImg:Image IntfImg:Name="Long Sunken Surround.png"/>

                <IntfImg:Image IntfImg:Name="Short Blue.png"/>
                <IntfImg:Image IntfImg:Name="Short Cyan.png"/>
                <IntfImg:Image IntfImg:Name="Short Gold.png"/>
                <IntfImg:Image IntfImg:Name="Short Green.png"/>
                <IntfImg:Image IntfImg:Name="Short Light Purple.png"/>
                <IntfImg:Image IntfImg:Name="Short Purple.png"/>
                <IntfImg:Image IntfImg:Name="Short Red.png"/>
                <IntfImg:Image IntfImg:Name="Short Yellow.png"/>
                <IntfImg:Image IntfImg:Name="Short Sunken Surround.png"/>
            </IntfImg:Scope>

            <IntfImg:Scope IntfImg:Name="SmallNoAlpha">
                <IntfImg:Image IntfImg:Name="Ex Short Blue.png" IntfImg:Trans="Yes"/>
                <IntfImg:Image IntfImg:Name="Ex Short Cyan.png" IntfImg:Trans="Yes"/>
                <IntfImg:Image IntfImg:Name="Ex Short Gold.png" IntfImg:Trans="Yes"/>
                <IntfImg:Image IntfImg:Name="Ex Short Green.png" IntfImg:Trans="Yes"/>
                <IntfImg:Image IntfImg:Name="Ex Short Purple.png" IntfImg:Trans="Yes"/>
                <IntfImg:Image IntfImg:Name="Ex Short Red.png" IntfImg:Trans="Yes"/>
                <IntfImg:Image IntfImg:Name="Ex Short Yellow.png" IntfImg:Trans="Yes"/>

                <IntfImg:Image IntfImg:Name="Long Blue.png" IntfImg:Trans="Yes"/>
                <IntfImg:Image IntfImg:Name="Long Cyan.png" IntfImg:Trans="Yes"/>
                <IntfImg:Image IntfImg:Name="Long Gold.png" IntfImg:Trans="Yes"/>
                <IntfImg:Image IntfImg:Name="Long Green.png" IntfImg:Trans="Yes"/>
                <IntfImg:Image IntfImg:Name="Long Purple.png" IntfImg:Trans="Yes"/>
                <IntfImg:Image IntfImg:Name="Long Red.png" IntfImg:Trans="Yes"/>
                <IntfImg:Image IntfImg:Name="Long Yellow.png" IntfImg:Trans="Yes"/>

                <IntfImg:Image IntfImg:Name="Short Blue.png" IntfImg:Trans="Yes"/>
                <IntfImg:Image IntfImg:Name="Short Cyan.png" IntfImg:Trans="Yes"/>
                <IntfImg:Image IntfImg:Name="Short Gold.png" IntfImg:Trans="Yes"/>
                <IntfImg:Image IntfImg:Name="Short Green.png" IntfImg:Trans="Yes"/>
                <IntfImg:Image IntfImg:Name="Short Purple.png" IntfImg:Trans="Yes"/>
                <IntfImg:Image IntfImg:Name="Short Red.png" IntfImg:Trans="Yes"/>
                <IntfImg:Image IntfImg:Name="Short Yellow.png" IntfImg:Trans="Yes"/>
            </IntfImg:Scope>
        </IntfImg:Scope>

        <IntfImg:Scope IntfImg:Name="Glass">
            <IntfImg:Image IntfImg:Name="Long Blue.bmp" IntfImg:Trans="Yes"/>
            <IntfImg:Image IntfImg:Name="Long Light Blue.bmp" IntfImg:Trans="Yes"/>
            <IntfImg:Image IntfImg:Name="Long Purple.bmp" IntfImg:Trans="Yes"/>
            <IntfImg:Image IntfImg:Name="Short Light Blue.bmp" IntfImg:Trans="Yes"/>
            <IntfImg:Image IntfImg:Name="Short Purple.bmp" IntfImg:Trans="Yes"/>
        </IntfImg:Scope>

        <IntfImg:Scope IntfImg:Name="Glass2">
            <IntfImg:Scope IntfImg:Name="Combo">
                <IntfImg:Image IntfImg:Name="Blue Blank.png"/>
                <IntfImg:Image IntfImg:Name="Blue Blank Emph.png"/>
                <IntfImg:Image IntfImg:Name="Cyan Blank.png"/>
                <IntfImg:Image IntfImg:Name="Cyan Blank Emph.png"/>
                <IntfImg:Image IntfImg:Name="Green Blank.png"/>
                <IntfImg:Image IntfImg:Name="Green Blank Emph.png"/>
                <IntfImg:Image IntfImg:Name="Purple Blank.png"/>
                <IntfImg:Image IntfImg:Name="Purple Blank Emph.png"/>
                <IntfImg:Image IntfImg:Name="Red Blank.png"/>
                <IntfImg:Image IntfImg:Name="Red Blank Emph.png"/>
                <IntfImg:Image IntfImg:Name="Yellow Blank.png"/>
                <IntfImg:Image IntfImg:Name="Yellow Blank Emph.png"/>
            </IntfImg:Scope>

            <IntfImg:Scope IntfImg:Name="MediaPlayer">
                <IntfImg:Image IntfImg:Name="Extra Large.png"/>
                <IntfImg:Image IntfImg:Name="Extra Large Surround.png"/>
                <IntfImg:Image IntfImg:Name="Large.png"/>
                <IntfImg:Image IntfImg:Name="Large Surround.png"/>
                <IntfImg:Image IntfImg:Name="Larger.png"/>
                <IntfImg:Image IntfImg:Name="Larger Surround.png"/>
                <IntfImg:Image IntfImg:Name="Medium.png"/>
                <IntfImg:Image IntfImg:Name="Medium Surround.png"/>
                <IntfImg:Image IntfImg:Name="Small.png"/>
                <IntfImg:Image IntfImg:Name="Small Surround.png"/>
            </IntfImg:Scope>

            <IntfImg:Scope IntfImg:Name="Membrane">
                <IntfImg:Image IntfImg:Name="Extra Short Pressed.png"/>
                <IntfImg:Image IntfImg:Name="Extra Short Unpressed.png"/>
                <IntfImg:Image IntfImg:Name="Long Pressed.png"/>
                <IntfImg:Image IntfImg:Name="Long Unpressed.png"/>
                <IntfImg:Image IntfImg:Name="Medium Pressed.png"/>
                <IntfImg:Image IntfImg:Name="Medium Unpressed.png"/>
                <IntfImg:Image IntfImg:Name="Short Pressed.png"/>
                <IntfImg:Image IntfImg:Name="Short Unpressed.png"/>
            </IntfImg:Scope>

            <IntfImg:Scope IntfImg:Name="Oblong">
                <IntfImg:Image IntfImg:Name="Blue Left Half.png"/>
                <IntfImg:Image IntfImg:Name="Blue Right Half.png"/>
                <IntfImg:Image IntfImg:Name="Green Left Half.png"/>
                <IntfImg:Image IntfImg:Name="Green Right Half.png"/>
                <IntfImg:Image IntfImg:Name="Red Left Half.png"/>
                <IntfImg:Image IntfImg:Name="Red Right Half.png"/>
                <IntfImg:Image IntfImg:Name="Sunken Black Glass.png"/>
                <IntfImg:Image IntfImg:Name="Sunken Black Glass Sep.png"/>
                <IntfImg:Image IntfImg:Name="Long Small Black Glass.png"/>
                <IntfImg:Image IntfImg:Name="Long Small Blue Glass.png"/>
                <IntfImg:Image IntfImg:Name="Long Small Green Glass.png"/>
                <IntfImg:Image IntfImg:Name="Long Small Gold Glass.png"/>
                <IntfImg:Image IntfImg:Name="Long Small Red Glass.png"/>
            </IntfImg:Scope>

            <IntfImg:Scope IntfImg:Name="Round">
                <IntfImg:Image IntfImg:Name="Blue Blank.png"/>
                <IntfImg:Image IntfImg:Name="Blue Blank Emph.png"/>
                <IntfImg:Image IntfImg:Name="Cyan Blank.png"/>
                <IntfImg:Image IntfImg:Name="Cyan Blank Emph.png"/>
                <IntfImg:Image IntfImg:Name="Green Blank.png"/>
                <IntfImg:Image IntfImg:Name="Green Blank Emph.png"/>
                <IntfImg:Image IntfImg:Name="Purple Blank.png"/>
                <IntfImg:Image IntfImg:Name="Purple Blank Emph.png"/>
                <IntfImg:Image IntfImg:Name="Red Blank.png"/>
                <IntfImg:Image IntfImg:Name="Red Blank Emph.png"/>
                <IntfImg:Image IntfImg:Name="Yellow Blank.png"/>
                <IntfImg:Image IntfImg:Name="Yellow Blank Emph.png"/>
            </IntfImg:Scope>

            <IntfImg:Scope IntfImg:Name="SmallRound">
                <IntfImg:Image IntfImg:Name="Blue Blank.png"/>
                <IntfImg:Image IntfImg:Name="Cyan Blank.png"/>
                <IntfImg:Image IntfImg:Name="Green Blank.png"/>
                <IntfImg:Image IntfImg:Name="Purple Blank.png"/>
                <IntfImg:Image IntfImg:Name="Red Blank.png"/>
                <IntfImg:Image IntfImg:Name="Yellow Blank.png"/>
            </IntfImg:Scope>

            <IntfImg:Scope IntfImg:Name="SmallRoundNoAlpha">
                <IntfImg:Image IntfImg:Name="Blue Blank.png" IntfImg:Trans="Yes"/>
                <IntfImg:Image IntfImg:Name="Cyan Blank.png" IntfImg:Trans="Yes"/>
                <IntfImg:Image IntfImg:Name="Green Blank.png" IntfImg:Trans="Yes"/>
                <IntfImg:Image IntfImg:Name="Purple Blank.png" IntfImg:Trans="Yes"/>
                <IntfImg:Image IntfImg:Name="Red Blank.png" IntfImg:Trans="Yes"/>
                <IntfImg:Image IntfImg:Name="Yellow Blank.png" IntfImg:Trans="Yes"/>
            </IntfImg:Scope>

            <IntfImg:Scope IntfImg:Name="Square">
                <IntfImg:Image IntfImg:Name="Blue Panel.png"/>
                <IntfImg:Image IntfImg:Name="Green Panel.png"/>
                <IntfImg:Image IntfImg:Name="Long Black Glass.png"/>
                <IntfImg:Image IntfImg:Name="Long Black Glass 2.png"/>
                <IntfImg:Image IntfImg:Name="Long Black Glass 2 Pressed.png"/>
                <IntfImg:Image IntfImg:Name="Long Blue Glass.png"/>
                <IntfImg:Image IntfImg:Name="Long Surround 1.png"/>
                <IntfImg:Image IntfImg:Name="Red Panel.png"/>
                <IntfImg:Image IntfImg:Name="Short Black Glass.png"/>
                <IntfImg:Image IntfImg:Name="Short Black Glass 2.png"/>
                <IntfImg:Image IntfImg:Name="Short Black Glass 2 Pressed.png"/>
                <IntfImg:Image IntfImg:Name="Short Black Vert Glass.png"/>
                <IntfImg:Image IntfImg:Name="Short Blue Glass.png"/>
                <IntfImg:Image IntfImg:Name="Short Blue Vert Glass.png"/>
                <IntfImg:Image IntfImg:Name="Short Surround 1.png"/>
            </IntfImg:Scope>

        </IntfImg:Scope>

        <IntfImg:Scope IntfImg:Name="Plastic">
            <IntfImg:Scope IntfImg:Name="Oblong">
                <IntfImg:Image IntfImg:Name="Large Grey.png"/>
                <IntfImg:Image IntfImg:Name="Medium Grey.png"/>
                <IntfImg:Image IntfImg:Name="Small Grey.png"/>
                <IntfImg:Image IntfImg:Name="Tiny Grey.png"/>
            </IntfImg:Scope>

            <IntfImg:Scope IntfImg:Name="SmallRound">
                <IntfImg:Image IntfImg:Name="Blue.png"/>
                <IntfImg:Image IntfImg:Name="Green.png"/>
                <IntfImg:Image IntfImg:Name="Purple.png"/>
                <IntfImg:Image IntfImg:Name="Red.png"/>
                <IntfImg:Image IntfImg:Name="Sunken Grey.png"/>
                <IntfImg:Image IntfImg:Name="Yellow.png"/>
            </IntfImg:Scope>

            <IntfImg:Scope IntfImg:Name="Square">
                <IntfImg:Image IntfImg:Name="Medium Raised Grey.png"/>
                <IntfImg:Image IntfImg:Name="Medium-Small Raised Grey.png"/>
                <IntfImg:Image IntfImg:Name="Small Raised Blue.png"/>
                <IntfImg:Image IntfImg:Name="Medium Raised Blue.png"/>
            </IntfImg:Scope>

        </IntfImg:Scope>

    </IntfImg:Scope>


    <!-- Some analog clock related images -->
    <IntfImg:Scope IntfImg:Name="Clocks">

        <IntfImg:Scope IntfImg:Name="Faces">
            <IntfImg:Image IntfImg:Name="BlueGlass.png"/>
        </IntfImg:Scope>

        <IntfImg:Scope IntfImg:Name="Hands">

            <IntfImg:Scope IntfImg:Name="SimpleWhite">
                <IntfImg:Image IntfImg:Name="Hour_0.png"/>
                <IntfImg:Image IntfImg:Name="Hour_1.png"/>
                <IntfImg:Image IntfImg:Name="Hour_2.png"/>
                <IntfImg:Image IntfImg:Name="Hour_3.png"/>
                <IntfImg:Image IntfImg:Name="Hour_4.png"/>
                <IntfImg:Image IntfImg:Name="Hour_5.png"/>
                <IntfImg:Image IntfImg:Name="Hour_6.png"/>
                <IntfImg:Image IntfImg:Name="Hour_7.png"/>
                <IntfImg:Image IntfImg:Name="Hour_8.png"/>
                <IntfImg:Image IntfImg:Name="Hour_9.png"/>
                <IntfImg:Image IntfImg:Name="Hour_10.png"/>
                <IntfImg:Image IntfImg:Name="Hour_11.png"/>

                <IntfImg:Image IntfImg:Name="Min_0.png"/>
                <IntfImg:Image IntfImg:Name="Min_1.png"/>
                <IntfImg:Image IntfImg:Name="Min_2.png"/>
                <IntfImg:Image IntfImg:Name="Min_3.png"/>
                <IntfImg:Image IntfImg:Name="Min_4.png"/>
                <IntfImg:Image IntfImg:Name="Min_5.png"/>
                <IntfImg:Image IntfImg:Name="Min_6.png"/>
                <IntfImg:Image IntfImg:Name="Min_7.png"/>
                <IntfImg:Image IntfImg:Name="Min_8.png"/>
                <IntfImg:Image IntfImg:Name="Min_9.png"/>

                <IntfImg:Image IntfImg:Name="Min_10.png"/>
                <IntfImg:Image IntfImg:Name="Min_11.png"/>
                <IntfImg:Image IntfImg:Name="Min_12.png"/>
                <IntfImg:Image IntfImg:Name="Min_13.png"/>
                <IntfImg:Image IntfImg:Name="Min_14.png"/>
                <IntfImg:Image IntfImg:Name="Min_15.png"/>
                <IntfImg:Image IntfImg:Name="Min_16.png"/>
                <IntfImg:Image IntfImg:Name="Min_17.png"/>
                <IntfImg:Image IntfImg:Name="Min_18.png"/>
                <IntfImg:Image IntfImg:Name="Min_19.png"/>

                <IntfImg:Image IntfImg:Name="Min_20.png"/>
                <IntfImg:Image IntfImg:Name="Min_21.png"/>
                <IntfImg:Image IntfImg:Name="Min_22.png"/>
                <IntfImg:Image IntfImg:Name="Min_23.png"/>
                <IntfImg:Image IntfImg:Name="Min_24.png"/>
                <IntfImg:Image IntfImg:Name="Min_25.png"/>
                <IntfImg:Image IntfImg:Name="Min_26.png"/>
                <IntfImg:Image IntfImg:Name="Min_27.png"/>
                <IntfImg:Image IntfImg:Name="Min_28.png"/>
                <IntfImg:Image IntfImg:Name="Min_29.png"/>

                <IntfImg:Image IntfImg:Name="Min_30.png"/>
                <IntfImg:Image IntfImg:Name="Min_31.png"/>
                <IntfImg:Image IntfImg:Name="Min_32.png"/>
                <IntfImg:Image IntfImg:Name="Min_33.png"/>
                <IntfImg:Image IntfImg:Name="Min_34.png"/>
                <IntfImg:Image IntfImg:Name="Min_35.png"/>
                <IntfImg:Image IntfImg:Name="Min_36.png"/>
                <IntfImg:Image IntfImg:Name="Min_37.png"/>
                <IntfImg:Image IntfImg:Name="Min_38.png"/>
                <IntfImg:Image IntfImg:Name="Min_39.png"/>

                <IntfImg:Image IntfImg:Name="Min_40.png"/>
                <IntfImg:Image IntfImg:Name="Min_41.png"/>
                <IntfImg:Image IntfImg:Name="Min_42.png"/>
                <IntfImg:Image IntfImg:Name="Min_43.png"/>
                <IntfImg:Image IntfImg:Name="Min_44.png"/>
                <IntfImg:Image IntfImg:Name="Min_45.png"/>
                <IntfImg:Image IntfImg:Name="Min_46.png"/>
                <IntfImg:Image IntfImg:Name="Min_47.png"/>
                <IntfImg:Image IntfImg:Name="Min_48.png"/>
                <IntfImg:Image IntfImg:Name="Min_49.png"/>

                <IntfImg:Image IntfImg:Name="Min_50.png"/>
                <IntfImg:Image IntfImg:Name="Min_51.png"/>
                <IntfImg:Image IntfImg:Name="Min_52.png"/>
                <IntfImg:Image IntfImg:Name="Min_53.png"/>
                <IntfImg:Image IntfImg:Name="Min_54.png"/>
                <IntfImg:Image IntfImg:Name="Min_55.png"/>
                <IntfImg:Image IntfImg:Name="Min_56.png"/>
                <IntfImg:Image IntfImg:Name="Min_57.png"/>
                <IntfImg:Image IntfImg:Name="Min_58.png"/>
                <IntfImg:Image IntfImg:Name="Min_59.png"/>

            </IntfImg:Scope>

        </IntfImg:Scope>

    </IntfImg:Scope>


    <!-- All the general images are under here -->
    <IntfImg:Scope IntfImg:Name="General">

        <IntfImg:Image IntfImg:Name="Small Black Check.png"/>

        <IntfImg:Scope IntfImg:Name="Arrows">
            <IntfImg:Image IntfImg:Name="Down Arrow 1.png"/>
            <IntfImg:Image IntfImg:Name="Left Arrow 1.png"/>
            <IntfImg:Image IntfImg:Name="Right Arrow 1.png"/>
            <IntfImg:Image IntfImg:Name="Up Arrow 1.png"/>
        </IntfImg:Scope>

        <IntfImg:Scope IntfImg:Name="Decorative">
            <IntfImg:Image IntfImg:Name="Corner 1 LR.png" IntfImg:Trans="Yes"/>
            <IntfImg:Image IntfImg:Name="Corner 1 UL.png" IntfImg:Trans="Yes"/>
            <IntfImg:Image IntfImg:Name="Corner 2 LR.png" IntfImg:Trans="Yes"/>
            <IntfImg:Image IntfImg:Name="Corner 2 UL.png" IntfImg:Trans="Yes"/>
            <IntfImg:Image IntfImg:Name="Flower 1.png" IntfImg:Trans="Yes"/>
            <IntfImg:Image IntfImg:Name="Flower 2.png" IntfImg:Trans="Yes"/>
            <IntfImg:Image IntfImg:Name="Flower 3.png" IntfImg:Trans="Yes"/>
            <IntfImg:Image IntfImg:Name="Flower 4.png" IntfImg:Trans="Yes"/>
            <IntfImg:Image IntfImg:Name="Vines 1.png" IntfImg:Trans="Yes"/>
            <IntfImg:Image IntfImg:Name="Vines 2.png" IntfImg:Trans="Yes"/>
        </IntfImg:Scope>

        <IntfImg:Scope IntfImg:Name="Icons">
            <IntfImg:Image IntfImg:Name="Accessibility.png"/>
            <IntfImg:Image IntfImg:Name="Address Book.png"/>
            <IntfImg:Image IntfImg:Name="Backup.png"/>
            <IntfImg:Image IntfImg:Name="Blue Cog.png"/>
            <IntfImg:Image IntfImg:Name="Briefcase.png"/>
            <IntfImg:Image IntfImg:Name="Calculator.png"/>
            <IntfImg:Image IntfImg:Name="Card Deck.png"/>
            <IntfImg:Image IntfImg:Name="Check Mark.png"/>
            <IntfImg:Image IntfImg:Name="Chrome Ball.png"/>
            <IntfImg:Image IntfImg:Name="Date Time.png"/>
            <IntfImg:Image IntfImg:Name="Document.png"/>
            <IntfImg:Image IntfImg:Name="Driver.png"/>
            <IntfImg:Image IntfImg:Name="Exclamation.png"/>
            <IntfImg:Image IntfImg:Name="File Transfer.png"/>
            <IntfImg:Image IntfImg:Name="Film Reel.png"/>
            <IntfImg:Image IntfImg:Name="Folder.png"/>
            <IntfImg:Image IntfImg:Name="Font Folder.png"/>
            <IntfImg:Image IntfImg:Name="Font.png"/>
            <IntfImg:Image IntfImg:Name="Globe.png"/>
            <IntfImg:Image IntfImg:Name="Group.png"/>
            <IntfImg:Image IntfImg:Name="Information.png"/>
            <IntfImg:Image IntfImg:Name="Internet Explorer.png"/>
            <IntfImg:Image IntfImg:Name="Keys.png"/>
            <IntfImg:Image IntfImg:Name="Magnifying Glass.png"/>
            <IntfImg:Image IntfImg:Name="Media Document.png"/>
            <IntfImg:Image IntfImg:Name="Media Document 2.png"/>
            <IntfImg:Image IntfImg:Name="Moon.png"/>
            <IntfImg:Image IntfImg:Name="Music Document.png"/>
            <IntfImg:Image IntfImg:Name="Music Folder.png"/>
            <IntfImg:Image IntfImg:Name="Not Allowed.png"/>
            <IntfImg:Image IntfImg:Name="Note Pad.png"/>
            <IntfImg:Image IntfImg:Name="Open Envelope.png"/>
            <IntfImg:Image IntfImg:Name="Open Folder.png"/>
            <IntfImg:Image IntfImg:Name="Paint Brushes.png"/>
            <IntfImg:Image IntfImg:Name="Phone Call.png"/>
            <IntfImg:Image IntfImg:Name="Pie Chart.png"/>
            <IntfImg:Image IntfImg:Name="Question Mark.png"/>
            <IntfImg:Image IntfImg:Name="Recycler.png"/>
            <IntfImg:Image IntfImg:Name="Schedule.png"/>
            <IntfImg:Image IntfImg:Name="Search Document.png"/>
            <IntfImg:Image IntfImg:Name="Search Folder.png"/>
            <IntfImg:Image IntfImg:Name="Shield.png"/>
            <IntfImg:Image IntfImg:Name="Star.png"/>
            <IntfImg:Image IntfImg:Name="Sun.png"/>
            <IntfImg:Image IntfImg:Name="User Search.png"/>
            <IntfImg:Image IntfImg:Name="Video Document.png"/>
            <IntfImg:Image IntfImg:Name="Video Folder.png"/>
            <IntfImg:Image IntfImg:Name="Weather 1.png"/>
            <IntfImg:Image IntfImg:Name="Weather 2.png"/>
            <IntfImg:Image IntfImg:Name="Web Search.png"/>
            <IntfImg:Image IntfImg:Name="Windows Player.png"/>
            <IntfImg:Image IntfImg:Name="World.png"/>
            <IntfImg:Image IntfImg:Name="X Mark.png"/>
            <IntfImg:Image IntfImg:Name="X Mark 2.png"/>
            <IntfImg:Image IntfImg:Name="Zip File.png"/>
        </IntfImg:Scope>
    </IntfImg:Scope>


    <!-- All the hardware related images are under here -->
    <IntfImg:Scope IntfImg:Name="Hardware">

        <IntfImg:Scope IntfImg:Name="Icons">
            <IntfImg:Image IntfImg:Name="Camera.png"/>
            <IntfImg:Image IntfImg:Name="CD-R Disc.png"/>
            <IntfImg:Image IntfImg:Name="CD-ROM Disc.png"/>
            <IntfImg:Image IntfImg:Name="CD-RW Disc.png"/>
            <IntfImg:Image IntfImg:Name="Cell Phone.png"/>
            <IntfImg:Image IntfImg:Name="Computer System.png"/>
            <IntfImg:Image IntfImg:Name="Controller.png"/>
            <IntfImg:Image IntfImg:Name="Designer.png"/>
            <IntfImg:Image IntfImg:Name="Digital Disc.png"/>
            <IntfImg:Image IntfImg:Name="Disc Drive.png"/>
            <IntfImg:Image IntfImg:Name="DVD Disc.png"/>
            <IntfImg:Image IntfImg:Name="DVD Drive.png"/>
            <IntfImg:Image IntfImg:Name="DVD-R Disc.png"/>
            <IntfImg:Image IntfImg:Name="DVD-RAM Disc.png"/>
            <IntfImg:Image IntfImg:Name="DVD-ROM Disc.png"/>
            <IntfImg:Image IntfImg:Name="DVD-RW Disc.png"/>
            <IntfImg:Image IntfImg:Name="Floppy Drive.png"/>
            <IntfImg:Image IntfImg:Name="HandHeld.png"/>
            <IntfImg:Image IntfImg:Name="Hard Drive.png"/>
            <IntfImg:Image IntfImg:Name="Hardware.png"/>
            <IntfImg:Image IntfImg:Name="Keyboard.png"/>
            <IntfImg:Image IntfImg:Name="Light Off.png"/>
            <IntfImg:Image IntfImg:Name="Light On.png"/>
            <IntfImg:Image IntfImg:Name="Lock.png"/>
            <IntfImg:Image IntfImg:Name="Mouse.png"/>
            <IntfImg:Image IntfImg:Name="Music Disc.png"/>
            <IntfImg:Image IntfImg:Name="Muted Speaker.png"/>
            <IntfImg:Image IntfImg:Name="Network Connection.png"/>
            <IntfImg:Image IntfImg:Name="Network Dish.png"/>
            <IntfImg:Image IntfImg:Name="Network Drive.png"/>
            <IntfImg:Image IntfImg:Name="Network.png"/>
            <IntfImg:Image IntfImg:Name="Network2.png"/>
            <IntfImg:Image IntfImg:Name="PhoneFax.png"/>
            <IntfImg:Image IntfImg:Name="Portable Media.png"/>
            <IntfImg:Image IntfImg:Name="Power.png"/>
            <IntfImg:Image IntfImg:Name="Printer.png"/>
            <IntfImg:Image IntfImg:Name="Scanner.png"/>
            <IntfImg:Image IntfImg:Name="Serial Port.png"/>
            <IntfImg:Image IntfImg:Name="Speaker Music.png"/>
            <IntfImg:Image IntfImg:Name="Speaker.png"/>
            <IntfImg:Image IntfImg:Name="Tablet.png"/>
            <IntfImg:Image IntfImg:Name="Touch Screen.png"/>
            <IntfImg:Image IntfImg:Name="Video Camera.png"/>
            <IntfImg:Image IntfImg:Name="Volume Slider.png"/>
        </IntfImg:Scope>
    </IntfImg:Scope>


    <!-- All the halo images are under here -->
    <IntfImg:Scope IntfImg:Name="Halos">
        <IntfImg:Image IntfImg:Name="Blue Alpha.png"/>
        <IntfImg:Image IntfImg:Name="Gray Scale Alpha.png"/>
        <IntfImg:Image IntfImg:Name="Red Alpha.png"/>
    </IntfImg:Scope>


    <!--
       - This section contains general purpose icon type images
       -->
    <IntfImg:Scope IntfImg:Name="Icons">
        <IntfImg:Scope IntfImg:Name="Deans">
            <IntfImg:Image IntfImg:Name="Audio.png"/>
            <IntfImg:Image IntfImg:Name="Bulb.png"/>
            <IntfImg:Image IntfImg:Name="Globe.png"/>
            <IntfImg:Image IntfImg:Name="Movies.png"/>
            <IntfImg:Image IntfImg:Name="Tools.png"/>
            <IntfImg:Image IntfImg:Name="WatchTV.png"/>
            <IntfImg:Image IntfImg:Name="Weather.png"/>
        </IntfImg:Scope>

        <IntfImg:Scope IntfImg:Name="General">
            <IntfImg:Image IntfImg:Name="HVAC.png"/>
            <IntfImg:Image IntfImg:Name="Security.png"/>
        </IntfImg:Scope>
    </IntfImg:Scope>


    <!--
       - This section contains some image sets that are designed to work
       - together as a whole.
       -->
    <IntfImg:Scope IntfImg:Name="ImgSets">
        <IntfImg:Scope IntfImg:Name="Antique">
            <IntfImg:Image IntfImg:Name="Amber LED.png"/>
            <IntfImg:Image IntfImg:Name="Bottom Area.png"/>
            <IntfImg:Image IntfImg:Name="Bottom Area 1024.png"/>
            <IntfImg:Image IntfImg:Name="Bottom Area 1280.png"/>
            <IntfImg:Image IntfImg:Name="Check Box Off.png"/>
            <IntfImg:Image IntfImg:Name="Check Box On.png"/>
            <IntfImg:Image IntfImg:Name="Ex Large Entry Fld.png"/>
            <IntfImg:Image IntfImg:Name="Green LED.png"/>
            <IntfImg:Image IntfImg:Name="Horz Prog Bar.png"/>
            <IntfImg:Image IntfImg:Name="Horz Prog Bar Mask.png"/>
            <IntfImg:Image IntfImg:Name="Horz Prog Bar Overlay.png"/>
            <IntfImg:Image IntfImg:Name="Horz Slider Scale.png"/>
            <IntfImg:Image IntfImg:Name="Horz Slider Thumb.png"/>
            <IntfImg:Image IntfImg:Name="Horz Slider Thumb Small.png"/>
            <IntfImg:Image IntfImg:Name="Info Area.png"/>
            <IntfImg:Image IntfImg:Name="Info Area_2 800.png"/>
            <IntfImg:Image IntfImg:Name="Info Area_2 1024.png"/>
            <IntfImg:Image IntfImg:Name="Info Area_2 1280.png"/>
            <IntfImg:Image IntfImg:Name="Large Entry Fld.png"/>
            <IntfImg:Image IntfImg:Name="Large Horz Popup.png"/>
            <IntfImg:Image IntfImg:Name="Large Horz Sunken Panel.png"/>
            <IntfImg:Image IntfImg:Name="LED Blank.png"/>